### ISSUE TITLE
The dom-repeat example is broken

### ISSUE THREAD

**Issue by mvysny** [vaadin/docs#100]
The example at https://vaadin.com/docs-beta/v14/flow/polymer-templates/tutorial-template-list-bindings/ doesn't work because of this bug: https://github.com/Polymer/polymer/issues/4135

The workaround is to use `<template is="dom-repeat" items="{{employees}}">`

**Comment by jouni** [comment]
Fixed in https://github.com/vaadin/docs/commit/249194ef2de1409a2e60c3163940fccfce870e45
