### ISSUE TITLE
[form-layout] Add an example of using custom-field for multiple fields inside a form-item

### ISSUE THREAD

**Issue by vursen** [vaadin/docs#1005]
Placing multiple fields directly to a form-item is deprecated (https://github.com/vaadin/web-components/pull/3221). Using a custom-field is recommended instead. 

It would make sense if we had an example in the form-layout docs that showed how fields have to be wrapped with a custom-field when there is a need for multiple fields inside a single form-item.

**Comment by knoobie** [comment]
Please add a flow example (following a11y best practices) as well. :)

**Comment by archiecobbs** [comment]
See also this ultimately unsatisfying discussion here: https://github.com/vaadin/web-components/issues/4353

**Comment by jouni** [comment]
What are the most common use cases that you would want to see?

**Comment by knoobie** [comment]
I think an example everybody could understand is an address where e.g. street and housenumber are different fields but the backend can only take a single field for both (sadly not so uncommon). 

The custom field should therefore have two text fields and map the single string by some splitting logic on binder read and combining both fields when writing the binder's field value.

**Comment by archiecobbs** [comment]
Agreed. Here's a typical example of such a form in one of my applications:

<img width="919" alt="Screen Shot 2022-12-21 at 8 51 35 AM" src="https://user-images.githubusercontent.com/545866/208933554-fa165793-bad0-4024-8cbc-1231cbe83c4d.png">

**Comment by jouni** [comment]
From a technical point of view, the example @archiecobbs posted looks like stacked “field groups” or “field sets” (i.e. the HTML `<fieldset>` element), with multiple individual “fields” laid out horizontally inside them. I believe that might give is an accessible way to create such form layouts. That implies that neither Form Item or Custom Field is the right tool for the job.
