### ISSUE TITLE
Live examples missing imports for Web Components

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/docs#101]
The examples on the page https://vaadin.com/docs-beta/latest/flow/application/application-events/ don't have ts files with imports of the required Web Components for the Flow counterparts

**Comment by jouni** [comment]
@magi42, can you fix this?

**Comment by magi42** [comment]
Yes, I'll make some TS examples to contain those.

**Comment by jouni** [comment]
Seems to be fixed.
