### ISSUE TITLE
Node.js configuration documentation small fixes

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/docs#1047]
In [this page](https://vaadin.com/docs/v14/flow/configuration/node-js) the link is not rendered correctly (as shown in this screenshot), and it would be great to improve the documentation regarding the "Project-local installation". It should clarify that using the "project_dir/node" location for node (by using the frontend-maven-plugin to automatically download it and place it in there), it will be used automatically by flow-maven-plugin (or also vaadin-maven-plugin?)

![image](https://user-images.githubusercontent.com/28312758/151414289-3ba72d33-0d15-4479-9b94-afb4d97746bc.png)

**Comment by jouni** [comment]
Thanks, I fixed the link formatting.

**Comment by tarekoraby** [comment]
The issue is fixed.
