### ISSUE TITLE
Collaboration Engine docs for V18+ have @Push on the wrong class

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#105]
https://vaadin.com/docs/v18/ce/tutorial.html#ce.tutorial.push
The `@Push` annotation should be on the `AppShellConfigurator` class, not the main layout, in V18 and later.

**Comment by pekam** [comment]
Closing as a duplicate of https://github.com/vaadin/collaboration-engine-internal/issues/483
