### ISSUE TITLE
Migration guide V22 - V23

### ISSUE THREAD

**Issue by joheriks** [vaadin/docs#1051]
Create a migration guide informing the user what they may need to consder when upgrading from V22:
- [x] Use Java 11 or newer in the project (describe how to set the version in `pom.xml`). If using the `maven-failsafe-plugin` in your project, `jaxb` and other potential dependencies (https://maven.apache.org/surefire/maven-failsafe-plugin/java9.html) needs to be added (give example what to add to `pom.xml`).
- [x] The default package manager is now again `npm`. If you want to continue using `pnpm`, set `vaadin.pnpm.enable=true`.
- [x] If going with npm, ensure minimum npm version is 8.3 due to use of `overrides` section.
- [x] Node is now always used from `~/.vaadin` if global installation is incompatible

**Comment by caalador** [comment]
https://docs.google.com/document/d/1_aeyegOGBC30JjZey8sy4lX4Qk0xRm99yduW44jZHfg/edit#heading=h.pmexwvfg3yws
