### ISSUE TITLE
Sample apps linked from the tutorial don't use the same version as the documentation

### ISSUE THREAD

**Issue by jcoleman-scott** [vaadin/docs#1087]
### Description of the bug

Example: when downloading a starter app from the v22 tutorial: 

https://vaadin.com/docs/v22/flow/tutorial/project-setup

a v14 app is born:

https://start.vaadin.com/?preset=flow-crm-tutorial&preset=partial-latest&dl

The tutorial also says there is a data model included, but there is not.

The app created by the link in the "Starting a project" section:

https://vaadin.com/docs/v22/flow/guide/start

DOES match the version selected:

https://start.vaadin.com/?preset=latest

This is all especially confusing when trying to add Vaadin to an existing Spring Boot project. Perhaps a guide on how to do that would be useful?

### Expected behavior

Sample apps should match documentation.

### Minimal reproducible example

Download a starter app from the button here:

https://vaadin.com/docs/v22/flow/tutorial/project-setup

### Versions

- Vaadin / Flow version: 14/22/23
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by tarekoraby** [comment]
Thanks for the report. Due to a refactoring that occurred yesterday in start.vaadin.com, links like this one
```
https://start.vaadin.com/?preset=flow-crm-tutorial&preset=partial-latest&dl
```
Should be now replaced with
```
https://start.vaadin.com/dl?preset=flow-crm-tutorial&preset=partial-latest
```

I made the necessary changes to the tutorials and they should now match the structure. 

But I didn't understand what you mean in relation to the "Starting a project" section. You say that "This is all especially confusing when trying to add Vaadin to an existing Spring Boot project". Could you please clarify how https://vaadin.com/docs/v22/flow/guide/start is confusing in that regard?

**Comment by jcoleman-scott** [comment]
Somehow I ended up with a v14 sample project and a v22 sample project. It looks like I started applying annotations to my views by referencing the v22 sample/starter, then halfway through my refactor I downloaded a new starter project so I could mimic badges (which were not included in any of the views I selected for my v22 starter). Unknowingly, and apparently even using the same button in the same tutorial, I downloaded a v14 sample project. So at no point did I see an application class that was annotated with @Theme, which meant I did not apply the annotation and badge never got included in my app. Upon realizing that I had two different starter versions, I investigated the upgrade path from 14 to 22 and saw that the movement of the @Theme annotation to the application class was the first thing listed…tldr: I was looking in the wrong places in the wrong versions of starter apps for examples of annotations to apply to my Spring Boot project.



Please note, no coverage can be bound, altered or terminated nor can a claim be reported via telephone or email message unless we respond with a confirmation. This email is not intended to nor does it change the terms and conditions of your actual policies and/or contracts. Information provided is for general illustration and/or informational purposes only and should not be construed as tax or legal advice. Email Confidentiality Notice: The information contained in this transmission is confidential, proprietary or privileged and may be subject to protection under the law, including the Health Insurance Portability and Accountability Act (HIPAA). The message is intended for the sole use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are notified that any use, distribution or copying of the message is strictly prohibited and may subject you to criminal or civil penalties. If you received this transmission in error, please contact the sender immediately by replying to this email and delete the material from any computer.

**Comment by jcoleman-scott** [comment]
Right, that’s why I filed the bug report as recommended in the Discord chat. :D



Please note, no coverage can be bound, altered or terminated nor can a claim be reported via telephone or email message unless we respond with a confirmation. This email is not intended to nor does it change the terms and conditions of your actual policies and/or contracts. Information provided is for general illustration and/or informational purposes only and should not be construed as tax or legal advice. Email Confidentiality Notice: The information contained in this transmission is confidential, proprietary or privileged and may be subject to protection under the law, including the Health Insurance Portability and Accountability Act (HIPAA). The message is intended for the sole use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are notified that any use, distribution or copying of the message is strictly prohibited and may subject you to criminal or civil penalties. If you received this transmission in error, please contact the sender immediately by replying to this email and delete the material from any computer.
