### ISSUE TITLE
Complete the "Security" section of the Fusion docs

### ISSUE THREAD

**Issue by vlukashov** [vaadin/docs#110]
When looking for security-related documentation for Vaadin Fusion, I would like the the [Security Overview](https://vaadin.com/docs-beta/latest/fusion/security/fusion-security-overview/) page to include the same content as the matching [Security Overview](https://vaadin.com/docs-beta/latest/flow/security/security-overview/) page for Flow.

Specifically, the security section of the Fusion docs should cover the following topics:
 - **Security in Vaadin Applications**
   Gives an introduction to the Vaadin Fusion security architecture and how it works in practice. (Where and how does it determine if a user has access? Where does the auth info come from?) Further, release and security practices in developing and releasing Vaadin products are described (How would I replace the default Spring Security setup with something else? Which classes can I provide my own implementations for, and how?)
 - **Best Practices**
   Describes various best practices for configuring access control for back-end endpoints, authentication with Spring Security, access to the user authentication data.
- **Common Vulnerabilities**
   Describes common vulnerabilities such as SQL injections, cross-site request forgeries (CSRF/XSRF), cross-site scripting (XSS), and so forth.

For each new Fusion-focused article consider how to unify / align / cross-reference it with the corresponding Flow article to avoid repeating the same text in two places.

**Comment by jouni** [comment]
> avoid repeating the same text in two places.

The Asciidoc `include::[]` directive is useful in keeping the texts consistent and avoid copy-paste. I don’t think it’s a problem if the same content appears in two places in the docs. Repetition isn’t an issue.

**Comment by haijian-vaadin** [comment]
Could split the ticket into 2:
1. restructure the common part
- **Common Vulnerabilities** seems the same for Fusion and Flow, could use include::[] to include the current Flow article to fusion. The code examples in Fusion could be replaced with TS.
- **Best Practices** also shares common content with Flow
- The 2 adding login form with spring security articles could be combined into 1 authentication article?
- could use [tagging regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/)
- Could be other changes as long as the end result would be aligned with the ticket desription.
2. New article for application overview for the **Security in Vaadin Applications**

**Comment by haijian-vaadin** [comment]
Close this Epic as all the tickets have been closed or in review
