### ISSUE TITLE
Add deployment preview to all branches

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1112]
It would be very useful to have Amplify preview (or any other preview) showing for PRs on all branches. Currently, this is importantly missing for Hilla, v22, and v8 branches.

**Comment by tarekoraby** [comment]
@mvap can you please help in making this happen?

**Comment by tarekoraby** [comment]
Amplify preview added to latest, hilla, v14 & v22 branches.

**Comment by jouni** [comment]
I’ll disable the Netlify preview builds then.
