### ISSUE TITLE
Upgrade Bakery to V23

### ISSUE THREAD

**Issue by joheriks** [vaadin/docs#1158]
https://github.com/vaadin/bakery-app-starter-flow-spring

While migrating, for each migration issue not already ticketed or in the existing [major-to-major upgrade guide](https://vaadin.com/docs/latest/upgrading/?from=14&to=23&isFlow=true&isFusion=true&isSpring=true&isTypeScript=true&isCustomStyling=true&isInstructionsDisplayed=true), create an issue in column Demo app. Task is complete when app is upgraded (migrated app in new branch v23, app works and ITs pass) and all new migration issues have been ticketed.

**Comment by tomivirkki** [comment]
Migrated in https://github.com/vaadin/bakery-app-starter-flow-spring/tree/v23

Issues created:
- https://github.com/vaadin/docs/issues/1180
- https://github.com/vaadin/docs/issues/1186
- https://github.com/vaadin/docs/issues/1189
- https://github.com/vaadin/docs/issues/1190
- https://github.com/vaadin/docs/issues/1204
- https://github.com/vaadin/docs/issues/1205
- https://github.com/vaadin/docs/issues/1212
- https://github.com/vaadin/docs/issues/1185
- https://github.com/vaadin/docs/issues/1184
