### ISSUE TITLE
Upgrade Customer project #1 to V23

### ISSUE THREAD

**Issue by joheriks** [vaadin/docs#1167]
While migrating, for each migration issue not already ticketed or in the existing [major-to-major upgrade guide](https://vaadin.com/docs/latest/upgrading/?from=14&to=23&isFlow=true&isFusion=true&isSpring=true&isTypeScript=true&isCustomStyling=true&isInstructionsDisplayed=true), create an issue in the "Customer projects" column. Task is complete when app is upgraded (migrated app in new branch v23, app works and ITs pass) and all new migration issues have been ticketed.

- See https://github.com/vaadin/feature-ideas/issues/21 for details.

**Comment by tomivirkki** [comment]
Migrated

Issues created:
- https://github.com/vaadin/docs/issues/1243
