### ISSUE TITLE
Spring MVC example is confusing

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/docs#117]
The example for Spring MVC configuration in the documentation looks like 1 class
![image](https://user-images.githubusercontent.com/51313578/105009895-bcb1a700-5a43-11eb-84f6-2795f3b5f716.png)

And it can result to one class:
```
public class SampleWebAppInitializer extends VaadinMVCWebAppInitializer {

@Override
protected Collection<Class<?>> getConfigurationClasses() {
return Collections.singletonList(
SampleConfiguration.class);
}

@Configuration
@ComponentScan
@PropertySource("classpath:application.properties")
public class SampleConfiguration {

}
}
```

With this code, the application is not working:
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type

**Comment by jouni** [comment]
Closed in #118
