### ISSUE TITLE
Document how to manage generated files in version control

### ISSUE THREAD

**Issue by joheriks** [vaadin/docs#1179]
Vaadin 23 generates a plethora of files in the project directory, including but not limited to:
```
frontend/generated/index.ts
frontend/generated/vaadin-featureflags.ts
frontend/generated/vaadin.ts
frontend/index.html
tsconfig.json
types.d.ts
vite.config.js
vite.generated.js
webpack.config.js
webpack.generated.js
```

We are currently missing a concise recommendation on which files should be added to version control and which should be ignored, and why. One potential location for this article is:
https://vaadin.com/docs/latest/flow/configuration

A link to this article should be provided in the V14 - V23 migration guide.

**Comment by samie** [comment]
@Artur- can confirm that this is correct, but something I configured today:

Default, or If you have set `com.vaadin.experimental.viteForFrontendBuild=false` in your `src/main/resources/vaadin-featureflags.properties`
webpack.config.js - Frontend compilation specification
webpack.generated.js (generated, should be ignored in .gitignore)

If you have set `com.vaadin.experimental.viteForFrontendBuild=true` in your `src/main/resources/vaadin-featureflags.properties`
- vite.config.js  - Frontend compilation specification
- vite.generated.js (generated, should be ignored in .gitignore)
