### ISSUE TITLE
Router: logout link needs to have router-ignore attribute

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/docs#1180]
Vaadin router intercepts a logout link navigation so that a possible Spring Security logout URL doesn't work as expected.
Related: https://vaadin.com/forum/thread/18464564/spring-security-logout-support

This can be worked around by adding a `router-ignore` attribute to the logout anchor

**Comment by joheriks** [comment]
Explain that the attribute is generally needed to bypass Vaadin router, and use logout as the example.
