### ISSUE TITLE
Document migrating from PolymerTemplate to LitTemplate

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/docs#1204]
`PolymerTemplate` is deprecated in favor of `LitTemplate`.
Add migration instructions for what needs to be changed.

Make sure to cover `TemplateModel`, `@Include`, `@Encode`

**Comment by joheriks** [comment]
Also how to migrate away from `com.vaadin.flow.component.polymertemplate.EventHandler` shoud be documented.

**Comment by joheriks** [comment]
Need to document:

- `TemplateModel` doesn't exist any more
- To transfer data to the client, use `Element::setProperty{Bean,List}` (and custom DTOs if you have something that you need to include / exclude from your data object; if building the DTO requires conversion of some data fields, run the converter manually)
- To transfer data from the client, use `@ClientCallable`

**Comment by TatuLund** [comment]
Would it make sense to link external comprehensive tutorials on topic, say like https://medium.com/@westbrook/turning-up-to-lit-fd19aab2ce9a
