### ISSUE TITLE
JustifyContentMode.BETWEEN described to have no spacing before first item, but has it in example (v14 only)

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/docs#1219]
The basic layout page describes usage of JustifyContentMode.BETWEEN for both Horizontal Layout and Vertical Layout. 
https://vaadin.com/docs/v14/ds/components/basic-layouts
Description for BETWEEN includes:
> Available space is distributed evenly between items. No space is added before the first item, or after the last.

Yet, the actual examples show space before first item. 
The space can be removed by setting `layout.setSpacing(false);` and this probably should be described / addressed. 

![image](https://user-images.githubusercontent.com/80950643/159696549-bcd71d5e-0bff-4152-b0a8-da519a3354db.png)
![image](https://user-images.githubusercontent.com/80950643/159696649-61121832-47b4-447f-a194-b2f877eab1a7.png)

**Comment by jouni** [comment]
Spacing should be disabled for disabled for all of these modes, so that the ::before pseudo element is not affecting the outcome.
