### ISSUE TITLE
Pre-release role on dialog footer isn't working

### ISSUE THREAD

**Issue by knoobie** [vaadin/docs#1319]
## expectation

Footer has the same information about pre-release as the header feature

## example 

![6FF54433-BF01-4EB6-8B0A-8C37164E9A6C](https://user-images.githubusercontent.com/3968629/163663924-568f6cfc-fac6-42dd-8bf4-67d29edc783d.png)

**Comment by jouni** [comment]
Thanks for noticing. This seems like a bug in our Design System Publisher. The AsciiDoc source for those headings looks identical to me, so the label should be similarly visible.
