### ISSUE TITLE
Add documentation for the Lit renderer directives

### ISSUE THREAD

**Issue by vursen** [vaadin/docs#1356]
Now that every Vaadin web component with renderers provides Lit renderer directives, they need to be mentioned somewhere in the documentation.

There are at least several ways how to attain that:

### 1. "Usage with Lit" section

Add a section `Usage with Lit` to every component page with renderers that would show you a list of directives that the component provides and how to use them.

### 2. "Usage with Lit" separate page

Add a separate page `Usage with Lit` that in particular would assemble the full list of directives of all the components with renderers. Cross-link this page with the corresponding component pages.

### 3. Use directives in TypeScript examples by default

Update all the TypeScript examples that use renderers so that they use the corresponding Lit directives instead.

---

Related to https://github.com/vaadin/web-components/issues/266

**Comment by jouni** [comment]
The third option seems feasible from the point of view that our recommended stack does use Lit, and it improves DX. If we choose that, then I think it implies that we should instead add a guide that shows how to use the components without Lit (similar to the second option).

**Comment by rolfsmeds** [comment]
Agree with the above. Regarding the non-Lit guidance, wouldn't the jsdoc of each component be a better fit for that than the component's `/docs` page?

**Comment by web-padawan** [comment]
We already have JSDoc examples for using `renderer` functions in web components so I hope this should be enough.
Also there are code examples in GitHub / npm package READMEs - see [dialog](https://github.com/vaadin/web-components/tree/master/packages/dialog#vaadindialog) package for a minimal example.

**Comment by tomivirkki** [comment]
The ["Replace Template Elements With Renderers"](https://github.com/vaadin/docs/blob/latest/articles/upgrading/recommended-changes/instructions/_polymertemplate.adoc#replace-template-elements-with-renderers) section of the V14->V23 migration guide should also be updated to use the new renderer directives. A lot of the boilerplate related to using the raw renderer functions can be removed from the instructions.
