### ISSUE TITLE
Callouts are not showing properly in Lit templates

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1382]
Callouts are not showing properly in Lit templates. For example, in [step 4 of the Hilla quick start](https://hilla.dev/docs/tutorials/quickstart/#step-4-create-a-reactive-ui-in-typescript) guide, this is how the callouts look like:

![image](https://user-images.githubusercontent.com/42799254/168537625-2c4d0432-c60c-4047-abcd-ec9812170612.png)

**Comment by jouni** [comment]
Not 100% certain, but I think this is the same issue as https://github.com/vaadin/docs-app/pull/231

**Comment by jouni** [comment]
This issue has been fixed in DS Publisher, and will be part of the upcoming 2.1 release.
