### ISSUE TITLE
Incorrect code formatting at Flow application-lifecycle

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1388]
Flow application-lifecycle article has several instances of incorrect code formatting (starting [here](https://vaadin.com/docs/latest/flow/advanced/application-lifecycle/#application.lifecycle.session.init)). 

![image](https://user-images.githubusercontent.com/42799254/168787491-0b53b9f1-300d-42fb-bfe5-46751b297141.png)

**Comment by jouni** [comment]
There’s some odd AsciiDoc content in the source. I don’t think this is a bug in DSP. Rather a bug in the docs source. 
![image](https://user-images.githubusercontent.com/66382/168894886-a44711d2-46f9-40fb-9894-96d88e8f5b6c.jpeg)

**Comment by tarekoraby** [comment]
Yeah, I saw that code, and I wasn't sure about its purpose. I guess we can just remove that.
