### ISSUE TITLE
The page content motion is distracting when scrolling up  

### ISSUE THREAD

**Issue by johannesh2** [vaadin/docs#139]
The sticky header appearing when I scroll up in docs is fancy but suits more for product landing pages and other marketing pages. When it's used in reference documentation it hurts the reading experience because while trying to find a certain section or code snippet that would help me, I keep scrolling up and down. In this kind of use case, the menu motion paired with the left and right TOC movement is quite prominent and distracting.

**Comment by jouni** [comment]
Adjusted the layout logic/styles. Let me know if it’s enough!
