### ISSUE TITLE
Add instructions for using a database 

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1409]
Add instructions on how to use a database in a Flow or a Hilla application. The instructions should highlight the option of using an embedded H2 database. It should also clarify the steps needed to use non-embedded databases during development (such as MySQL, MariaDB, and PostgreSQL). 

The instructions could be placed under https://vaadin.com/docs/latest/flow/integrations.

**Comment by platosha** [comment]
For Hilla, it makes sense to point to existing Spring Boot database integration articles.

**Comment by tarekoraby** [comment]
I think the guides should be:

- Based on a simple project downloaded from start.vaadin.com
- Based on Spring Boot and Spring Data
- Show the minimal amount of steps to get the database connected with a Vaadin application (no need to go deep into the details of each database)
- Assume that people already have the databases installed and configured (we can just provide a link to the databases' installation websites)

**Comment by jouni** [comment]
I assume this is now solved with https://vaadin.com/docs/latest/integrations/databases
