### ISSUE TITLE
Missing @Theme annotation in Flow tutorial

### ISSUE THREAD

**Issue by dmitrilc** [vaadin/docs#1424]
Mentioning of the annotation `@Theme` at https://vaadin.com/docs/latest/flow/tutorial/navigation-and-layouts/#creating-the-parent-layout is probably a mistake as this annotation has not been used on **ListView.java** earlier in the tutorial.

The most recent version of **ListView.java** since the mentioning of `@Theme` was at https://vaadin.com/docs/latest/flow/tutorial/handling-view-state/#showing-the-selected-contact-in-the-form, which was not annotated with `@Theme`.

**Comment by tarekoraby** [comment]
Tha t looks like a mistake indeed. This tutorial is based on a project that is generated in start.vaadin.com, and that project has `@Theme` annotation in `Application.java`.
