### ISSUE TITLE
Little contrast between code and text

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1430]
At least on Windows + Chrome, there appears to be very little contrast between code and text. For example, this is how the first paragraph of https://vaadin.com/docs/latest/flow/routing/url-parameters looks like:

![image](https://user-images.githubusercontent.com/42799254/171814051-1d10844e-f24d-48b3-97b5-3d434d84d681.png)

With dark mode, the issue is the same

![image](https://user-images.githubusercontent.com/42799254/171814187-62a492ca-e60d-4ac0-9549-a4999da8525f.png)

**Comment by jouni** [comment]
Fixed the indiscernible background color (on the `BeforeEnter` part for example) for the dark mode theme in DSP: https://github.com/vaadin/docs-app/commit/c4f23b1ef3c3e65c34143d478909a7a05a6806d2

The other custom styles defined for vaadin.com docs, that’s more debatable. Personally, I’ve aimed to keep them closer to regular paragraph text, to make reading easier. I’m not sure how much more they need to stand out. Currently they use a dark color, bolder font weight, and extra spacing on the sides, to separate from the regular text.

The OS you use makes a difference as well. Here’s how they look on macOS:
<img width="690" alt="Screen Shot 2022-06-03 at 11 33 29" src="https://user-images.githubusercontent.com/66382/171818953-677bae1e-4dcd-4960-b664-c011c4140d8a.png">

<img width="693" alt="Screen Shot 2022-06-03 at 11 33 48" src="https://user-images.githubusercontent.com/66382/171818996-06d5f049-bd84-4282-ac2b-1065a03361ac.png">

Using another font might help. Currently we are using the default OS monospace font (`"ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"`), not sure which one Windows users will get.

**Comment by jouni** [comment]
I would not label this as a DSP issue. If a custom DS wants to emphasize the inline code snippets more, they can do that with the dedicated CSS custom props, `--docs-inline-code-color` and `--docs-inline-code-background-color`.

**Comment by jouni** [comment]
Using color for those pieces of text could make them look like links (either unvisited or visited), or if we use something more distinct like red, orange, or green, somewhat childish perhaps.

<img width="606" alt="Screen Shot 2022-06-03 at 11 46 43" src="https://user-images.githubusercontent.com/66382/171821141-5380da3f-4263-47d7-812c-52eb31850e43.png">

**Comment by tarekoraby** [comment]
How about changing the `background-color` rather than their color to make them more distinct?

**Comment by jouni** [comment]
The styles have been updated in DS Publisher. I consider this fixed. Please add a comment if you still think they need to stand out more.

**Comment by tarekoraby** [comment]
Looks good now 👍 

![image](https://user-images.githubusercontent.com/42799254/207576307-272ee7f2-b5a7-4c33-a37d-14048ca3d922.png)
