### ISSUE TITLE
Flow Push documentation sets the annotation on wrong class

### ISSUE THREAD

**Issue by pekam** [vaadin/docs#145]
[The `@Push` documentation for latest Vaadin version]( https://vaadin.com/docs-beta/latest/flow/advanced/push-configuration/#push.configuration.annotation) instructs to set the annotation "for the main layout or individual view of an application". This does not work. In the latest Vaadin versions, the `@Push` annotation must be set on `AppShellConfigurator` instead.

**Comment by eriklumme** [comment]
Searching for `@Push`, I found the following issues still:

https://vaadin.com/docs/latest/flow/advanced/server-push/#push.configuration.enabling

The example `Application` class only implements `SpringBootServletInitializer`. At least in the `20.0.0.alpha3` app I had laying around, it did not work without implementing `AppShellConfigurator`.

https://vaadin.com/docs/latest/flow/advanced/server-push#push.broadcaster

The example `BroadcasterView` is annotated with `@Push`.

https://vaadin.com/docs/latest/flow/advanced/server-push#push.access

The example `PushyView` is annotated with `@Push`.

https://vaadin.com/docs/latest/tools/mpr/configuration/push

Says to put `@Push` on any navigation target. Maybe it works differently with MPR?
