### ISSUE TITLE
Navigation title and topic title should be the same of URL Templates doc

### ISSUE THREAD

**Issue by dmitrilc** [vaadin/docs#1450]
For https://vaadin.com/docs/latest/flow/routing/templates, the navigation title and topic title are different (**URL Template** vs **Route Template**). The titles for both should be the same if they refer to the same concept.

![url template vs route templates](https://user-images.githubusercontent.com/4550185/172449367-1a4db9d5-a505-4efb-b756-6dda21517dd5.png)

**Comment by tarekoraby** [comment]
I think this could be handled as part of #1447.
