### ISSUE TITLE
Missing explanation for the colon in URL Template

### ISSUE THREAD

**Issue by dmitrilc** [vaadin/docs#1452]
The syntax

`:parameter_name[modifier][(regex)]` at https://vaadin.com/docs/latest/flow/routing/templates 

is preceded by a colon (`:`), but the explanations breaking up the syntax down does not clearly state what the colon does. 

If the parameter in the URL Template requires a colon as a prefix, then the doc should clearly say so.

**Comment by tarekoraby** [comment]
I think the colon is used to distinguish between a static route and a parameter to that route. 

If I do `@Route("user/:userID")` then this means that `userID` is parameter. In that case, the user of the app can enter something like `user/123-ASD` as the URL in the browser and access that view. 

Whereas without the colon,  `@Route("user/userID")` means that the user will reach this view only if they enter the URL `user/userID` in the browser.

**Comment by dmitrilc** [comment]
Should be handled as part of #1447
