### ISSUE TITLE
Document Lombok @EqualsAndHashCode problems with Grid

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#1496]
A frequent confusion is caused by Lombok's default @EqualsAndHashCode in the context of Grid. This should be covered by the documentation with an example.

From https://stackoverflow.com/a/72646870/3608089 : 
>  By default [Lombok] generates equals and hashcode that use all the properties of the entity. This does not work with Vaadin's data model, as it expects the beans to be invariant, i.e. changing value of properties like confirmationPhone should not affect the beans identity. You can solve this either 1. defining in Lomboks annotation that uses only the id or userId for the equals and hashcode. Or 2. Extend DataProvider and override getId method so that uses either one.

> Example of Lombok use below
```java
@Entity
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Table(name = "forms", schema = "click", catalog = "")
public class FormEntity {

    @EqualsAndHashCode.Include private long id;
    private String userId;
    private String requestorType;
    private String confirmationPhone;
    private Timestamp submittedDate;
    private int status;
    private Timestamp approvedDate;
    private String comments;
    private String organization;
    private PatientEntity patientEntity;
    ...
```

**Comment by tarekoraby** [comment]
I think there is a more general point which is that a proper implementation of equals and hashcode is needed (even without using Lombok) for many Vaadin components, like the grid, to behave properly.

**Comment by OlliTietavainenVaadin** [comment]
The Lombok way of generating equals and hashcode is just such a common gotcha that it should be explicitly mentioned, in my opinion

**Comment by tarekoraby** [comment]
To clarify, we need to document both:

1. The importance of having a proper implementation of equals and hashcode for many Vaadin components, like the grid, to behave properly. If those are not properly implemented, then the Vaadin component will not be able to distinguish between the different items added to it. 
2. The specific use case of Lombok

**Comment by tarekoraby** [comment]
I'm unsure though about where this information should be added. Some options are:

- https://vaadin.com/docs/latest/components/grid/flow
- https://vaadin.com/docs/latest/binding-data/data-provider
- Somewhere under https://vaadin.com/docs/latest/advanced

**Comment by OlliTietavainenVaadin** [comment]
I would go for the data-provider docs, and link that from the Grid docs.

**Comment by dmitrilc** [comment]
Though not directly related, JPA Buddy, which is automatically recommended by IntelliJ, has a linter for this:

Using @EqualsAndHashCode for JPA entities is not recommended. It can cause severe performance and memory consumption issues. 
 Inspection info: This inspection checks that @lombok.EqualsAndHashCode used in JPA entities

Related reading: https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong

**Comment by dmitrilc** [comment]
I'm trying to reproduce the OP's problem. It seems like the *select-all* button only shows up if setting grid content from an in-memory data structure.

Found this in Grid's java docs.

>         /*
>          * The visibility of the selectAll checkbox depends on whether the
>          * DataProvider is inMemory or not. When changing the DataProvider, its
>          * visibility needs to be revalidated.
>          */

Debugging shows that this code snippet

```java
if (getSelectionModel() instanceof GridMultiSelectionModel) {
    GridMultiSelectionModel<T> model = (GridMultiSelectionModel<T>) getSelectionModel();
    model.setSelectAllCheckboxVisibility(
            model.getSelectAllCheckboxVisibility());
}
```

is indeed called even if its enclosing method is marked deprecated.

Related class
https://vaadin.com/api/platform/23.1.6/com/vaadin/flow/component/grid/GridMultiSelectionModel.SelectAllCheckboxVisibility.html

Even when trying to set visibility with

```java
((GridMultiSelectionModel<SamplePerson>) grid.getSelectionModel()).setSelectAllCheckboxVisibility(
        GridMultiSelectionModel.SelectAllCheckboxVisibility.VISIBLE);
```

`selectAll` button still won't show.

Attempting to manually add a `selectAll` button and then use 

`((GridMultiSelectionModel<SamplePerson>) grid.getSelectionModel()).selectAll();`

to trigger *select all* instead.
