### ISSUE TITLE
What jaxb version?

### ISSUE THREAD

**Issue by mmoser18** [vaadin/docs#1498]
https://vaadin.com/docs/latest/upgrading/essential-steps documents that "For Java 9+, the `maven-failsafe-plugin` requires `jaxb-impl` to be added." and also shows the dependency snippet for Maven but with `${jaxb.version}` only.

So: WHAT version is required here? Or how can one find out?

Please add the version or the steps to figure that out to the mentioned doc-page.

**Comment by tarekoraby** [comment]
According to https://maven.apache.org/surefire/maven-failsafe-plugin/java9.html, the required Jaxb version is 2.3.0.

But to my mind, an easier approach is to ensure that one using `maven-failsafe-plugin` version to 2.21 or higher.

**Comment by mmoser18** [comment]
Thanks and cheers!
