### ISSUE TITLE
Add instructions for handling long-running tasks

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1511]
Add instructions for handling long-running tasks. The instructions should show to:
- handle long-running processes in separate threads using `ExecutorService`.
- inform the user about the progress of the long-running process (for example using `ProgressBar`).
- update the UI once the long-running process is completed. 

For Flow, this is related to this cookbook recipe: https://cookbook.vaadin.com/long-running-task .

**Comment by dmitrilc** [comment]
I think similar documentation has already been written here https://github.com/vaadin/docs/blob/v14/articles/flow/advanced/tutorial-push-access.asciidoc? I don't see the equivalence for v23 though. Furthermore, I can't tell if this is outdated information or not, but the code in this doc matches the cookbook recipe.

If we are indeed required to lock the user session, then all UI _push_ updates must go through the `UI.access()` abstraction.

I also see that Spring's `@Async` and `@EnableAsync` already being used, so rolling our own Executor seems kind of overkill and would most likely be anti-pattern.

Based on this https://spring.io/guides/gs/async-method/, we really don't have to provide our own Executor, but I can provide an Executor bean if needed.

At this point, my plan is to:
1. Repurpose some information from https://github.com/vaadin/docs/blob/v14/articles/flow/advanced/tutorial-push-access.asciidoc, especially the session lock and the `UI.access` abstraction.
2. Add a ProgressBar to show progress.
3. Use `@Async` + `@EnableAsync` + `@Push`.
4. Maybe provide a custom Executor bean.
