### ISSUE TITLE
Hilla documentation is using outdated Fusion API

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1516]
Hilla docs continue to use outdated Fusion API. For example, at https://hilla.dev/docs/application/accessing-backend#creating-an-endpoint, `com.vaadin.fusion.Endpoint` is still being used.

These references should be updated.

**Comment by platosha** [comment]
Also `pom.xml` needs to be updated to use the latest Hilla release (`1.1`).

**Comment by jouni** [comment]
A good example of the problem with example code written in asciidoc files. Included from a proper source file, and we can catch these during the build.

**Comment by tarekoraby** [comment]
Fixed by #1589.
