### ISSUE TITLE
Mention the `eagerServerLoad` flag for a 404 response in the Router Exception Handling article

### ISSUE THREAD

**Issue by platosha** [vaadin/docs#1521]
The `eagerServerLoad` flag in Flow enables a 404 response for initial requests with client-side bootstrapping when the server-side route matching the requested path is not found.

By default with client-side bootstrapping (since Vaadin 15), without `eagerServerLoad` enabled, the server response is `200 OK` in that case to facilitate “single page” applications with client-side views.

The `Router Exception Handling` article currently describes the 404 response, which is only the case with the `eagerServerLoad` enabled. This is misleading, because the default behavior is different.

**Comment by tarekoraby** [comment]
@platosha that only applies to Flow docs? or is there also somewhere to mention this in Hilla's?
