### ISSUE TITLE
Issues with Google Cloud Tutorial

### ISSUE THREAD

**Issue by simasch** [vaadin/docs#1536]
[The Google Cloud tutorial](https://vaadin.com/docs/latest/production/cloud-providers/google) is not up-to-date.

I've created a blog post about two problems (Java version, memory limit).
It would be great if you can check it out and update the documentation accordingly. https://martinelli.ch/how-to-deploy-a-vaadin-application-to-google-cloud-app-engine/

**Comment by dmitrilc** [comment]
Ticket for NPE: https://github.com/vaadin/flow/issues/14164

**Comment by dmitrilc** [comment]
I was only able to reproduce the error 

> Exceeded soft memory limit of 256 MB

on a Vaadin Start project with the Master Detail template because I guess it needs more dependencies such as Spring Data.

I did not see that error on a Vaadin Start project with only the Hello World and About templates. I will add this as a note.

**Comment by dmitrilc** [comment]
If using the Maven plugin to deploy, the `app.yaml` file should be in the `src/main/appengine` according to https://cloud.google.com/appengine/docs/standard/java-gen2/configuring-your-app-with-app-yaml

This plugin is a great convenient tool, but manually linking the `app.yaml` with `--appyaml` is also an option.
