### ISSUE TITLE
Add note or guide on how to store sensitive data

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1547]
The [database guides](https://vaadin.com/docs/latest/integrations/databases) describe adding the necessary configurations to `application.properties`. These configurations, however, include usernames and passwords, which should not be committed to git (at least not in plain text).

Add a note to the database guides warning against such use, and provide a secure alternative to storing sensitive data (for example, using a separate `application.properties` file as described in Hilla docs: https://hilla.dev/docs/security/spring-stateless/#step-2-configure-spring-security).

**Comment by tarekoraby** [comment]
We can perhaps create a separate short guide under https://vaadin.com/docs/latest/security/advanced-topics, then link to that from the database guides.

**Comment by dmitrilc** [comment]
There are a lot of options for this https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config

`application.properties` file is option number 3.

I am trying to decide which method is simplest to recommend.

**Comment by dmitrilc** [comment]
Helpful link: https://spring.io/blog/2020/04/23/spring-tips-configuration
