### ISSUE TITLE
@Push being used on non-AppShellConfigurator classes in docs

### ISSUE THREAD

**Issue by dmitrilc** [vaadin/docs#1555]
I found the annotation `@Push` being used on non-`AppShellConfigurator` classes on two different instances in the docs.

1. https://cookbook.vaadin.com/long-running-task
```java
@Route("long-running-task")
// @Push (add it here or in your AppShellConfigurator implementation)
public class LongRunningTask extends VerticalLayout 
```
- Even though commented out, the comment still incorrectly states that `@Push` can be used on this class.
 
2. https://vaadin.com/docs/latest/advanced/server-push/#push.access
```java
@Push
@Route("push")
public class PushyView extends VerticalLayout 
```
```java
@Push
@Route("broadcaster")
public class BroadcasterView extends Div
```

When I try to use `@Push` on a non-`AppShellConfigurator` class, the app fails to start with the error below:
```
Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
    - @Push from com.example.application.views.LongRunningTask
```

Maybe `@Push` can be used on non-`AppShellConfigurator` classes in a legacy version, but it is no longer the case on v23.

**Comment by tarekoraby** [comment]
I created a PR to fix the comment in the cookbook: https://github.com/vaadin/cookbook/pull/263.

For the docs page (https://vaadin.com/docs/latest/advanced/server-push/#push.access), we can add a note similar to the one mentioned [here](https://vaadin.com/docs/latest/tools/ce/tutorial/#ce.tutorial.push) for collaboration Engine.

**Comment by dmitrilc** [comment]
It looks like there is already a section like that at 
https://vaadin.com/docs/latest/advanced/server-push/#push.configuration.pushmode
https://vaadin.com/docs/latest/advanced/server-push/#push.configuration.annotation

So I think that removing `@Push` from the example is adequate. The code compiles without the `@Push` and the routes are accessible.
