### ISSUE TITLE
Use new VaadinWebSecurity for Vaadin Spring Security

### ISSUE THREAD

**Issue by mshabarov** [vaadin/docs#1632]
Update [Securing Spring Boot Applications](https://vaadin.com/docs/latest/security/enabling-security#security-configuration-class) article with a new `VaadinWebSecurity` API introduced as a replacement for deprecated `WebSecurityConfigurerAdapter` [here](https://github.com/vaadin/flow/pull/14303):
- code example section https://vaadin.com/docs/latest/security/enabling-security/#security-configuration-class
- note that `VaadinWebSecurityConfigurerAdapter` can still be used but would be excluded in the later versions
- prepare a branch in https://github.com/vaadin/flow-crm-tutorial/blob/v23/src/main/java/com/example/application/security/SecurityConfig.java to update the code examples there as well.

**Comment by tarekoraby** [comment]
When we change the docs to use `VaadinWebSecurity`, let's add a small note mentioning the old `VaadinWebSecurityConfigurerAdapter` for 23.1 users. We can remove this note after 23.1 is no longer supported.
