### ISSUE TITLE
Add note discouraging putting interactive elements in input field Helper

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/docs#1646]
Placing interactive elements in the Helper slot of an input field component cannot be programmatically prevented, but is not officially supported and may cause issues (especially for accessibility but behavioral conflicts are also possible). This should be mentioned in [the documentation for the helper feature](https://vaadin.com/docs/latest/components/input-fields/#helper).

**Comment by web-padawan** [comment]
There is now a corresponding note added in #2337:

> In addition to plain text, helpers can contain components and HTML elements. However, complex and interactive content is likely to have accessibility issues.
