### ISSUE TITLE
Migrate docs from Webpack to Vite

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/docs#1655]
Currently, Docs uses Webpack for frontend build by enabling [the feature flag](https://github.com/vaadin/docs/blob/latest/src/main/resources/vaadin-featureflags.properties#L2). However, using Webpack with Vaadin is deprecated in favor of Vite since version 23.2 and the support will be dropped in the upcoming majors.

The following changes should be done to migrate Docs to Vite:
- Create a Vite configuration that does the same things as the current [Webpack config](https://github.com/vaadin/docs/blob/latest/webpack.config.js)
  - [Excludes all vaadin and polymer imports from the application JS bundle](https://github.com/vaadin/docs/blob/latest/webpack.config.js#L40-L68)
  - [Exports the `applyTheme` function to the global object as `window.__applyTheme`](https://github.com/vaadin/docs/blob/latest/webpack.config.js#L26-L38)
- Drop the Webpack feature flag
- Remove the Webpack config file

**Comment by vursen** [comment]
Does it mean that the DSPublisher config itself will be still using Webpack?

**Comment by jouni** [comment]
> Does it mean that the DSPublisher config itself will be still using Webpack?

Yes, Gatsby still uses webpack.
