### ISSUE TITLE
V23 docs missing CustomizedSystemMessages

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#1699]
The possibility of customizing system messages is not available in the V14 or V23 documentation. For V8, the instructions are found here: https://vaadin.com/docs/v8/framework/application/application-errors/#application.errors.systemmessages ; the functionality hasn't changed to my knowledge.

**Comment by jouni** [comment]
I wonder if you could simply copy the content from there to here: https://vaadin.com/docs/latest/advanced/custom-error-handler, as a first step?
