### ISSUE TITLE
Add information about offline license key

### ISSUE THREAD

**Issue by mrauturier** [vaadin/docs#1762]
https://gitlab.vaadin.com/vaadincom/webpage/-/issues/6534

in https://vaadin.com/docs/latest/configuration/licenses#offline-license-key

Add "When downloading your offline key, please remove .txt from the file name and rename the file from offlineKey.txt to offlineKey." between chapters "Each offline license key is tied to a machine ID.." and "Once you have downloaded the.."

**Comment by jouni** [comment]
Fixed in https://github.com/vaadin/docs/commit/b1f5bde35d2da365612b6011a2b7da9b42a5df48
