### ISSUE TITLE
Incorrect label on horizonal alignment example

### ISSUE THREAD

**Issue by MatthewVaadin** [vaadin/docs#1780]
In the Basic Layouts page, there is a live example for horizontal alignment. In the example, the radio button group has a title of "Vertical alignment". This should be "Horizontal alignment".

**Comment by jouni** [comment]
Thanks! Fixed in a2a83a7f11011eb6d053e79b5ddf0e4b0c537c4c

**Comment by yuriy-fix** [comment]
Closing as fixed via a2a83a7
