### ISSUE TITLE
Add docs for new global CSS loader feature (V20+)

### ISSUE THREAD

**Issue by Haprog** [vaadin/docs#193]
Add documentation for the feature and related deprecation implemented in https://github.com/vaadin/flow/pull/10036

**Comment by haijian-vaadin** [comment]
We have the [theming docs](https://vaadin.com/docs-beta/latest/theming/overview/), it probably fits into [Creating a Custom Theme](https://vaadin.com/docs-beta/latest/theming/creating-a-custom-theme/) or [Style Scopes](https://vaadin.com/docs-beta/latest/theming/style-scopes/), or maybe a separate article will also do.

**Comment by haijian-vaadin** [comment]
Could also take a look at the [Slack discussion](https://vaadin.slack.com/archives/CDNTYMS9H/p1613654911450200)

**Comment by jouni** [comment]
The theming docs are being restructured and partially rewritten. We have an article for Styling / Importing Style Sheets for Flow, and we should write the same article for Fusion where this new feature is documented.

**Comment by Haprog** [comment]
>The theming docs are being restructured and partially rewritten. We have an article for Styling / Importing Style Sheets for Flow, and we should write the same article for Fusion where this new feature is documented.

@jouni is there some WIP branch or open issue related to this (styling docs for Fusion)?
