### ISSUE TITLE
Document the usecases for using OSGi declarative services features with Vaadin

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/docs#194]
It's already possible to use every OSGi feature inside Vaadin application.
Sometimes it requires an additional boilerplate code and there is no way to use navigation target as a service via DS.
But it's quite easy to use DS anyway programmatically from any Vaadin view/component.

This should be documented with explanation why we don't provide this feature out of the box and all the ways that are possible already to do the same things.

This is the source of this documentation : 
https://github.com/vaadin/flow/issues/9107

**Comment by jouni** [comment]
Updated the title because I had trouble understanding that it’s not about design systems 😆
