### ISSUE TITLE
Unclear in which order route lifecycle methods are called

### ISSUE THREAD

**Issue by jouni** [vaadin/docs#1947]
From a comment in https://vaadin.com/docs/latest/routing/lifecycle

> Regarding BeforeEnterEvent : this page mentions BeforeEnterObserver and BeforeEnterListener, but this event is also passed to HasUrlParameter.setParameter() which is not mentioned, so it's not clear in which order the three interface methods are called.

**Comment by gtzluis** [comment]
Problably from this company:
https://app.hubspot.com/contacts/1840687/company/152540449

**Comment by HermanBovens** [comment]
@caalador there is still a mistake in the added pieces: the listener order for `BeforeEnterEvent` mentions `BeforeLeaveListener` and `BeforeLeaveObserver` instead of `BeforeEnterListener` and `BeforeEnterObserver`.

**Comment by jouni** [comment]
Yeah, indeed, thanks for catching that. I’ll fix it right away.
