### ISSUE TITLE
Improve session expiration documentation adding CustomizedSystemMessages usage details

### ISSUE THREAD

**Issue by mcollovati** [vaadin/docs#1954]
Session expiration behavior can be customized by providing a `CustomizedSystemMessages` through a `SystemMessagesProvider`.
A developer can, for example:

- set a URL to redirect the user on session expiration
- define caption and message for session expiration notification
- disable the notification

See also vaadin/flow#15476 for an example use case

**Comment by jouni** [comment]
Seems like a duplicate of #1699

**Comment by mcollovati** [comment]
Yes, you're right, it seems a duplicate.

But I would add that, in addition to document the `CustomizedSystemMessages` we may also need to improve the `Session expiration` paragraph of `Application Lifecycle` page to clarifying the difference between `VaadinSession` and HTTP session expiration and document the default behavior on client side when `VaadinSession` expires.

See comments on vaadin/flow#15476 for more context

Perhaps this ticket can be updated to handle the above changes
