### ISSUE TITLE
Update tutorial diagram

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1977]
Flow tutorial includes a diagram showing entities inherited from an `AbstractEntity` superclass: https://vaadin.com/docs/latest/tutorial/database-access.

However, start.vaadin.com no longer generates this superclass. So, the diagram should be updated accordingly.

**Comment by jouni** [comment]
Remove the AbstractEntity from the diagram, and the related blue arrow lines? What about the MappedSuperClass box?

**Comment by jouni** [comment]
♻️
