### ISSUE TITLE
Add compatibility matrix 

### ISSUE THREAD

**Issue by knoobie** [vaadin/docs#1985]
Currently it's sometimes hard to find information what versions of app servers / java / nodejs / servlet / spring boot or other Software Versions are needed / supported by Vaadin versions. 

Suggestion: 

Create a prominent table with Vaadin 14.x / 23.2 / 23.3 / 23.4 / 24 /..  and corresponding supported technologies. 

Example: 
- Vaadin 14 works with Java 8 - 17 (18/19?)
- Vaadin 23.x works with Java 11 - 17 (18/19?) 
- Vaadin 24.x works with Java 17+? 
- Vaadin 23.2 works with Spring Boot 2.x - 2.7.x 
- Vaadin 23.3 works with Spring Boot 2.7.x
- Vaadin 24.x works with Spring Boot 3 
- Vaadin 14 works with NodeJs 14.x - 18.x? (Build vs e.g. Server Requirement for Chart Server Side Rendering)
- Vaadin 23.x works with NodeJs 16.x - 18.x?
- Vaadin 24.x works with NodeJs 18.x+? 
- Vaadin 14 works with Servlet 4
- Vaadin 23.x works with Servlet 4 
- Vaadin 24 works with Servlet 6 (and probably 5) 
- Supported NPM Versions

**Comment by samie** [comment]
This sounds really important. Do you see it important to have both compile time and runtime compatibility?

**Comment by knoobie** [comment]
For Java and NodeJs (Chart server side rendering) it's probably needed to inform the user about both - compile and runtime compatibility. I don't think it matters for the others as much, even tho it could be interesting with Vaadin 24.0 and 24.1 with "Jetty / Servlet 5 support"
