### ISSUE TITLE
Old Hilla documentation is still visible

### ISSUE THREAD

**Issue by cromoteca** [vaadin/docs#2011]
See https://hilla.dev/docs/getting-started for example. Is this intended?

Related to https://github.com/vaadin/starters/issues/105

**Comment by jouni** [comment]
Hi! Thanks for raising the issue. Is is not intended, and it’s a known issue in our deployment scripts, that the old pages are not removed when a new website build is made. I’ll ping the relevant people about getting this fixed.

**Comment by jouni** [comment]
The deployment has been been updated, and old documentation pages are cleared when a new deployment happens.
