### ISSUE TITLE
Notification component does not set id in Vaadin 23 - Upgrade vaadin 14 to vaadin 23 migration guide

### ISSUE THREAD

**Issue by sujoykd** [vaadin/docs#2020]
Notification component in Vaadin 14 sets the id attribute to vaadin-notification-card
This is not done in Vaadin 23, so it needs to be documented in the upgrade guide, since applications may have css depending on this id.

**Comment by jouni** [comment]
I disagree that this should be part of the upgrade guide, at least on a general level. We are not going to document all internal API changes in the upgrade guides.

These CSS cases might be in the gray area, as it is easy for a developer to use them without knowing they are private API.

**Comment by yuriy-fix** [comment]
Closing as per @jouni's comment.
