### ISSUE TITLE
The DatePicker custom validation example should not promote Hilla Binder

### ISSUE THREAD

**Issue by vursen** [vaadin/docs#2021]
There is a ["Custom Validation"](https://vaadin.com/docs/latest/components/date-picker#custom-validation) example on the DatePicker page which is based on Hilla Binder. 

I believe we shouldn't promote Hilla Binder in our web component documentation. To avoid using Hilla Binder, we might extend DatePicker and override the `checkValidity` method. That should be the right way to customize validation when you deal with pure Vaadin web components.

Besides, the example has a bug. The error message disappears as soon as you click outside the date picker.

**Comment by web-padawan** [comment]
Now when we have merged Vaadin and Hilla in 24.4, Binder is used consistently by both Lit and React examples for `DatePicker`, `TimePicker` and `DateTimePicker`. Closing the issue as no longer relevant.
