### ISSUE TITLE
Documented NumberField.setStepButtonsVisible() doesn't exist in java API

### ISSUE THREAD

**Issue by amagnolo** [vaadin/docs#2060]
The setStepButtonsVisible() method mentioned in docs/articles/components/number-field/index.asciidoc doesn't seem to exist in java API.

**Comment by jouni** [comment]
Thanks for the report. Which version are you using?

**Comment by amagnolo** [comment]
23.2, but I couldn't find it even in earlier Vaadin versions (I checked up to 10)

**Comment by jouni** [comment]
I can at least see that method in AbstractNumberField in Vaadin 23.3. I think it was added in that version.

**Comment by amagnolo** [comment]
You're right, my bad. It was added in 23.3.
I got confused because I was looking for that method in BigDecimalField, but it doesn't extend AbstractNumberField, and then I messed up with API versions. 
I apologize for the inconvenience.
