### ISSUE TITLE
Push docs is confusing people with Spring class 

### ISSUE THREAD

**Issue by knoobie** [vaadin/docs#2093]
**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Tell us about your request**

^title says it all. The Push documentation adds a Spring class to any code example making it really hard to understand for newcomers. This class extending Spring is just not necessary. 

Link: https://vaadin.com/docs/latest/advanced/server-push

**Comment by mcollovati** [comment]
I think this has been fixed by #2148

**Comment by knoobie** [comment]
Looks like it 👍
