### ISSUE TITLE
Add vanilla web instructions for setting a whole app to dark theme

### ISSUE THREAD

**Issue by csuwildcat** [vaadin/docs#2118]
**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Tell us about your request**

In using the vanilla web components version of Vaadin I was unable to figure out how to set the entire app to use the dark theme for the components/styles until I read this comment from another person on Discord chat when I searched for older conversations on dark theme topics: https://discord.com/channels/732335336448852018/1018970318456500295/1019132762696994816. The docs instruct on how to do it in Java, but not for vanilla web implementations, so it would probably be a good idea to add this into the theme section of the docs alongside the Java instructions.

**Comment by web-padawan** [comment]
Fixed by #3261 with corresponding "vanilla" (Lit) and React code examples added. Closing.
