### ISSUE TITLE
Improve the error handling documentation in Fusion

### ISSUE THREAD

**Issue by platosha** [vaadin/docs#216]
We currently have the [Client-side exception](https://vaadin.com/docs-beta/latest/fusion/application/client-exceptions/) article, but it’s not enough. It should be updated (and possibly renamed) to also:

- Have an introduction telling about different sources of error, such as network errors, our endpoints throwing an exception, or application code on throws on the server or on the client.
- Describe endpoint client error classes (thrown from Connect.ts):
  - `EndpointError`
    - `EndpointValidationError`
  - `EndpointResponseError`
- Provide an example in TypeScript on how to catch them and handle them with respect to the error type
  - How to extract information specific to the error
  - How to show the notification for the user about the error
- Mention the offline data fallback use case with the link to the cachable wrapper article
- Mention that the form binder is handling `EndpointValidationError` from server-side during submission

Link to error handling from the Accessing Java Backend article.

**Comment by Haprog** [comment]
> link to the cachable wrapper article

I guess this means this: https://vaadin.com/docs-beta/latest/fusion/pwa/cache-client-side-data/ ?

**Comment by platosha** [comment]
Note the [error handling example in the offline article](https://vaadin.com/docs-beta/latest/flow/pwa/offline/#offline-typescript-views), could be replaced with a link to the error handling article, which should have the same or a similar example.

**Comment by joheriks** [comment]
Note: the above mentioned error handling example has moved to [here](https://vaadin.com/docs-beta/latest/guide/configuration/pwa/#offline-typescript-views). With the new layout it makes even more sense to replace the code snippet there with a link.
