### ISSUE TITLE
Document how to disable the express mode

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/docs#2206]
In this page:
https://vaadin.com/docs/next/configuration/development-mode/#front-end-development-server-for-easier-debugging

> Since Vaadin 24.0 this mode is used when the configuration parameter frontend.hotdeploy is set to true, see [Configuration Properties](https://vaadin.com/docs/next/configuration/properties) for more information.

But in the configuration page there is no frontend.hotdeploy properties.

**Comment by mcollovati** [comment]
Documentation for `frontend.hotdeploy` property is in #2157

**Comment by knoobie** [comment]
I think it should also be prominent documented on the new express mode page for people to "opt out" and go back to the old mode.

**Comment by mshabarov** [comment]
> I think it should also be prominent documented on the new express mode page for people to "opt out" and go back to the old mode.

Agree. I propose to show all the options how to setup this parameter directly in the dev mode page https://vaadin.com/docs/next/configuration/development-mode .

**Comment by caalador** [comment]
Fixed in #2404
