### ISSUE TITLE
Check the Vaadin 24 tutorial

### ISSUE THREAD

**Issue by jouni** [vaadin/docs#2216]
- Update JVM and other version requirements
- Remove notes about frontend builds (or move to a later phase if still needed)
- Address feedback in discussions/comments
    - At least one in Accessing the Database
- Verify that form/field validations work as before (because of the changes in the validation stuff)
- Replace strings with utility class enums 
    - At least in Navigation and App Layout and Login and Authentication
- Update screenshots
    - Some minor design updates for app layout and charts
- Check if there’s something to change for junit4 → junit5

**Comment by Mikaelsu** [comment]
https://github.com/vaadin/docs/pull/2237
