### ISSUE TITLE
Add using Vaadin components Fusion article

### ISSUE THREAD

**Issue by platosha** [vaadin/docs#222]
Create an article describing using Vaadin components in Fusion / Creating Applications section, after the “Creating a Main View” article.

List of topics to cover:

- One example of view using Vaadin components and endpoint data
- Dependencies:
  - No need to install existing platform dependences
  - How to install a third-party component, `vanilla-colorful` could be used as an example
- Import and using TypeScript type definition
- Common things with all components:
  - Visibility
  - Disabled state
  - Title attribute
- Where to find the list of components, their usage and API docs (links to DS, no need to repeat)
- Customising the look and feel (link to DS customisation)

Consider existing Quick Start Tutorial examples also: https://vaadin.com/docs-beta/latest/fusion/quick-start-tutorial/#litelement-basics

**Comment by joheriks** [comment]
If this article comes before "Accessing Java Backend", do we really want an example with endpoint data here? It will require explaining endpoints in this page as well, just to be repeated in the next.
