### ISSUE TITLE
Update configuration for Hilla 2

### ISSUE THREAD

**Issue by platosha** [vaadin/docs#2250]
Update the following articles for Hilla 2:

- The configuration article https://hilla.dev/docs/lit/reference/configuration/#java-compiler-options
  - Remove the “Preview feature” warning
  - Avoid the “multi-module engine” branding, as it is the only engine
  - Mention how to customise parser packages list to enable `@Endpoint` outside the application package scope
- The reactive endpoints article https://hilla.dev/docs/lit/guides/reactive-endpoints
  - Remove the “Preview feature” warning
- The feature flags article https://hilla.dev/docs/lit/reference/feature-flags is unnecessary, let us remove it

**Comment by cromoteca** [comment]
Fixed in https://github.com/vaadin/docs/pull/2361.
