### ISSUE TITLE
A lot console.log() errors while browsing the documentation

### ISSUE THREAD

**Issue by bwajtr** [vaadin/docs#2291]
Vaadin 24 docu: It seems that every docu page which contains some code snippets produces a lot of console errors :
![image](https://user-images.githubusercontent.com/1890879/225842101-75e2b3a0-d0fb-441e-9617-02c1a461cf5c.png)

Reproduced at least for Grid, Select, Message Input.
Chrome 111

**Comment by jouni** [comment]
The only error that we need to care about is the "iframeResizer is not function". The other ones are 404 responses for the requests we do to check whether the same page is available in other documentation versions.

Neither of those are related to pages with code snippets. The former happens on all pages that show a discussion/comments thread at the bottom of the page, and the latter happen on all pages.
