### ISSUE TITLE
Wrong slot for `new-button` in CRUD TypeScript example

### ISSUE THREAD

**Issue by cromoteca** [vaadin/docs#2324]
At https://vaadin.com/docs/latest/components/crud/#toolbar, both the custom and default buttons are visible. The custom button should target the `new-button` slot instead of being inside the `toolbar` one.

A revision of that page is recommended, as there's also https://github.com/vaadin/web-components/issues/5731 to consider.

**Comment by web-padawan** [comment]
Fixed by #2523.
