### ISSUE TITLE
Date Picker: custom validation TypeScript example throws an error

### ISSUE THREAD

**Issue by jouni** [vaadin/docs#2325]
<img width="1188" alt="Screenshot 2023-03-31 at 12 17 35" src="https://user-images.githubusercontent.com/66382/229079719-06cd2d62-1fc9-4454-bf64-be3de77fb6de.png">

**Comment by jouni** [comment]
This happens in production, using Vaadin 24.1.alpha1: https://vaadin.com/docs/latest/components/date-picker/#custom-validation

**Comment by vursen** [comment]
All the examples that are using Hilla Binder are broken.
