### ISSUE TITLE
Reproducible production build with "npm ci"

### ISSUE THREAD

**Issue by mshabarov** [vaadin/docs#2334]
**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Tell us about your request**

Document the feature in Flow for running `npm ci` command to build the frontend for production in a reproducible way.
Ways to enable it:
```
// vaadin-maven-plugin:
<configuration>
      <ciBuild>true</ciBuild>
</configuration>

// System property:
-Dci.build=true
```
See this implemented enhancement https://github.com/vaadin/flow/issues/15579 .
Should target Vaadin 24.1 and 14.10.
Have to be placed into https://vaadin.com/docs/latest/production/production-build and https://vaadin.com/docs/latest/configuration/properties

**Comment by jouni** [comment]
Did the #2347 and #2348 PRs address this issue already, and we can close this issue?

**Comment by mshabarov** [comment]
@jouni yes, thanks for asking (however it took 2 month for me to answer :) ), also this one gives a clues about this parameter https://github.com/vaadin/docs/pull/2450 .
