### ISSUE TITLE
Warn viewers of V14 tutorials

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#2338]
**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Tell us about your request**
More people still visit the [V14 tutorial](https://vaadin.com/docs/v14/flow/tutorial) than the latest one. It would be good for the V14 quick and long tutorials to have a prominent notice letting viewers know that the same tutorials are available for vLatest.

**Comment by jouni** [comment]
Added these kind of banners and admonitions to the quick start and long tutorial pages.

<img width="1290" alt="Screenshot 2023-05-19 at 15 32 23" src="https://github.com/vaadin/docs/assets/66382/6f6f117f-e7b1-4d96-b245-da32692878f0">
