### ISSUE TITLE
Remove mention(s) of Gradle in Hilla docs

### ISSUE THREAD

**Issue by Mikaelsu** [vaadin/docs#2369]
**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

The [in-depth tutorial](https://hilla.dev/docs/lit/start/in-depth#what-is-hilla) gives the impression that Hilla supports both Maven and Gradle. There could be other sections too.

**Comment by platosha** [comment]
Closing in favor of #2370
