### ISSUE TITLE
Broken links / redirects needed

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#2399]
https://vaadin.com/docs/latest/upgrading/V23-V24-steps -> should redirect to https://vaadin.com/docs/latest/upgrading/

**Comment by jouni** [comment]
Is that link in many places, do you know?

**Comment by jouni** [comment]
I mean, this feels like something we should fix at the source, instead of adding another redirect.

**Comment by OlliTietavainenVaadin** [comment]
The source is in this GitHub issue: https://github.com/vaadin/flow/issues/15665

**Comment by jouni** [comment]
I fixed the link in that issue description. I also added a "this page has moved" page for the old one, just in case there’s a link to it somewhere else: https://github.com/vaadin/docs/commit/505e7365ce4ea66315a05a992812ca190b7c75ea
