### ISSUE TITLE
Set up code formatter and linter

### ISSUE THREAD

**Issue by jouni** [vaadin/docs#24]
To avoid unnecessary nitpicking in code reviews, set up a code formatter(s) and linters.

- [x] TypeScript, HTML, CSS
- [ ] Java

**Comment by tomivirkki** [comment]
Set up Husky to run Prettier for staged ts- (and js, json) files on pre-commit: https://github.com/vaadin/docs/commit/1e43b2f56ac9b0bd56ba6e72c9417b54862801e7

**Comment by jouni** [comment]
I believe tuese are mostly in order now.
