### ISSUE TITLE
TypeScript Document links message input/list broken in V24

### ISSUE THREAD

**Issue by danielvanmil** [vaadin/docs#2400]
### Description

- Navigate to the V24 web components doc
- Try to open the TypeScript link in the message-input or message-list component

This opens https://cdn.vaadin.com/vaadin-web-components/?/#/elements/vaadin-message-input and shows a 403 forbidden

### Expected outcome

- The API doc

### Minimal reproducible example

See description

### Steps to reproduce

See description

### Environment

-

### Browsers

Chrome

**Comment by jouni** [comment]
Thanks for reporting! Should be fixed now (once the deployment happens, ~30 mins).
