### ISSUE TITLE
Duplicated contents on "Local Multi-Browser Tests" section

### ISSUE THREAD

**Issue by mcollovati** [vaadin/docs#2426]
The `Running Tests on Multiple Browsers` page contains the paragraph [Local Multi-Browser Tests](https://vaadin.com/docs/latest/testing/end-to-end/multiple-browsers/#local-multi-browser-tests) which has duplicated statement and code snippet

![image](https://github.com/vaadin/docs/assets/4648894/d5f80bbf-66ac-4150-b8f8-4068c4589c0e)

**Vote to prioritize:** add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by jouni** [comment]
Fixed in https://github.com/vaadin/docs/commit/93efb0e2bc578717d1a2f3cdc28c925afb707118 (v23) and https://github.com/vaadin/docs/commit/55d7462146adaeb04d2cc84c475369ce41ad4d4c (latest).
