### ISSUE TITLE
Grid drag and drop is not documented

### ISSUE THREAD

**Issue by mvysny** [vaadin/docs#253]
Flow: The page at https://github.com/vaadin/docs/edit/v14/articles/flow/components/tutorial-flow-grid.asciidoc should document Grid row drag'n'drop along with most common pitfalls (e.g. components in ComponentRenderer may consume the drag start event). Or as the very minimum link to this page: https://vaadin.com/components/vaadin-grid/java-examples/drag-and-drop

**Comment by jouni** [comment]
That Grid article (under the Flow section) is eventually going to be removed. The documentation should move to https://vaadin.com/docs-beta/latest/ds/components/grid/

Here’s the [design for Grid drag and drop documentation](https://docs.google.com/document/d/1SI-Htr0cpIKYwyj7jxOvvNiWL6klEChKYaN0YkrNI2w/edit#heading=h.93kyd81s3ngj).

**Comment by jouni** [comment]
The pitfalls you mention could be added, though.

**Comment by rolfsmeds** [comment]
@mvysny are there any other pitfalls that should be mentioned?

**Comment by mvysny** [comment]
@rolfsmeds no other pitfalls from my side, just the missing dnd docs and the one pitfall I mentioned.

**Comment by rolfsmeds** [comment]
I created a separate issue about that pitfall. Closing this as the other aspects are already covered.
