### ISSUE TITLE
Update Tutorial to not use deprecated Spring `authorizeHttpRequests()`

### ISSUE THREAD

**Issue by jouni** [vaadin/docs#2577]
Deprecated API has been replaced in Flow 24.2: https://github.com/vaadin/flow/pull/17136

Here's the related issue: https://github.com/vaadin/flow/issues/16872

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by Mikaelsu** [comment]
Updated the source code in [PR 169](https://github.com/vaadin/flow-crm-tutorial/pull/169). Will update the tutorial after it's merged.
