### ISSUE TITLE
Use NativeLabel instead of Label

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#2720]
At least one example, https://vaadin.com/docs/latest/components/grid#filtering, is using the deprecated `Label`. It should be changed to `NativeLabel` (also in other classes obviously).

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by web-padawan** [comment]
Usage of `Label` was replaced with `NativeLabel` in #2758. Closing.
