### ISSUE TITLE
Replace AppLayout RouterLink in Tabs examples

### ISSUE THREAD

**Issue by knoobie** [vaadin/docs#2821]
Title says it all. Replace the old examples with e.g. a simple nav/ul/li structure instead of this accessibility and DX nightmare.

--- 

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by jouni** [comment]
Correct me if I’m wrong, but this should be fixed now.
