### ISSUE TITLE
Hilla: [autogrid] Document order support for custom columns in Hilla 2.5+

### ISSUE THREAD

**Issue by taefi** [vaadin/docs#2990]
Document the way user should utilize the `key` property of custom columns in the `visibleColumns` to be able to define the column order for them as well.

This feature became available from 2.5 pre-releases. A _version label_ in the docs can help preventing potential confusions about which versions are supporting it.

**Comment by sissbruecker** [comment]
Has been resolved with https://github.com/vaadin/docs/pull/3022
