### ISSUE TITLE
Upload component can't be disabled

### ISSUE THREAD

**Issue by gsyjdcg** [vaadin/docs#2999]
**The "Upload" component can't be disabled**

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by rolfsmeds** [comment]
Closing as duplicate of https://github.com/vaadin/web-components/issues/1278
