### ISSUE TITLE
Update AppLayout samples to use SideNav instead of Tabs

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/docs#3055]
Title pretty much says it all.

And the mobile footer-nav sample could be refactored to use RouterLinks in a HorizontalLayout instead.

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by knoobie** [comment]
This would also close: https://github.com/vaadin/docs/issues/2821
