### ISSUE TITLE
Have a unified landing page for docs for any Vaadin version

### ISSUE THREAD

**Issue by Peppe** [vaadin/docs#308]
When you land to docs, you are automatically placed to the V14 version. It hides e.g. Fusion and component listing. To be able to see these, I have to know to switch the version to latest first. For a new user, it is hard to find these two things right now.

I suggest that we have a common landing page that is not version-specific. Features would then have tags "V14", "latest" to note if they are only relevant on a certain version selection. Being on V14 and clicking on Fusion would select the latest and open the Fusion documentation.

#### V14 landing page
![vaadin com_docs_v14_](https://user-images.githubusercontent.com/525503/112429797-d6be7d00-8d45-11eb-80df-96c2c51df599.png)

#### Latest landing page
![vaadin com_docs_latest_ (1)](https://user-images.githubusercontent.com/525503/112429790-d3c38c80-8d45-11eb-9c9b-cc862bbebab1.png)

**Comment by jouni** [comment]
Closing. The v14 docs do include component docs now, and a link to latest docs if you want to see Fusion.
