### ISSUE TITLE
The link to Lumo Colors on the Lumo Variants documentation page is broken

### ISSUE THREAD

**Issue by mlindfors** [vaadin/docs#3080]
There's a broken link in the documentation page here: 

https://vaadin.com/docs/latest/styling/lumo/lumo-variants, 

specifically in the Customize Dark Variant Colors tip box, pointing to the Lumo Colors documentation page. Currently the link is pointing to 
https://vaadin.com/styling/lumo/lumo-style-properties/color, 
when it more than likely should point to 
https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/color

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by jouni** [comment]
Fixed in #3085
