### ISSUE TITLE
Switching between version doesn't preserve the current page

### ISSUE THREAD

**Issue by tanbt** [vaadin/docs#314]
* In V14, open a page which is also available in V18+ version, such as Flow Overview page
  * https://vaadin.com/docs/latest/flow/overview
  * https://vaadin.com/docs/v14/flow/overview
 
* Select V18+ version on the top-left version menu

### Actual
The Flow Overview V14 page is redirected to the home page of V18+ https://vaadin.com/docs/latest/.

### Expect
The Flow Overview for V18+ is showed, i.e. https://vaadin.com/docs/latest/flow/overview

**Comment by jouni** [comment]
Not all pages have a corresponding page in the other version. And with the current implementation the versions are not aware of each other, and don’t know if there is a corresponding page in other versions.

I agree it would be nice to have this working for pages that exist across versions. But it needs some thinking/design to make it happen. 

The current behavior is consistent for all pages and therefore preferred (instead of giving a 404 on some pages while others would work).

**Comment by eriklumme** [comment]
This is by far my biggest gripe with the current docs. I frequently end up in the docs through Google, and for another version than the one I'm interested in.

So I switch versions, and then I have to find the page all over. Alternatively, I have to remember to change the version in the URL instead.

Of course changing the version should not result in a 404 if it doesn't exist. In that case, showing the docs start page is fine, with or without a notice that the page does not exist in the current version.

I don't know how it would be implemented, perhaps the current URL could be passed as a URL parameter when changing versions, and the docs site for the other version could forward to this page if it exists.

**Comment by jouni** [comment]
Here’s what I managed to implement (currently in testing/review, see previously linked PRs).

If the same exact path is found in both versions, then that page will simply be shown. If not, then you get the 404 page, but it’ll include potentially matching articles for you. For example, if you view the https://vaadin.com/docs/v14/flow/element-api/tutorial-properties-attributes page in V14 docs, and then switch to V21 (or the other way around), you’ll get something like this: https://deploy-preview-693--vaadin-docs-preview.netlify.app/flow/element-api/tutorial-properties-attributes?title=Element%20Properties%20and%20Attributes

![Screen_Shot_2021-08-12_at_14 17 30](https://user-images.githubusercontent.com/66382/129188504-b5f81ea3-d97d-4f12-ae64-928ce03c4b61.png)

The exact wording/layout of the 404 page is not necessarily final.


Note, that we can't really test switching versions in the PR preview builds, as we only have the latest version deployed there.

**Comment by jouni** [comment]
The implementation could be improved still, to use the same search index as the main built-in search uses, which is able to match article headings better (including sub-headings). But that index does not contain the page path, so it can't be used to recover from typos in the URL (e.g. you meant to type `/path/to/article` but you mistyped `path/to/aticle`).

That would help in cases such as the PWA topics, where they are separate pages/articles in V14 but a combined page in V21.

**Comment by jouni** [comment]
I ended up fixing this, at least for now, by always going to the same path/page when switching versions. This will result in 404s from many pages, but let’s see if that really is a problem.
