### ISSUE TITLE
PiT 24.4: Write a Hilla Upgrade Guide from 2.5 to 24.4

### ISSUE THREAD

**Issue by manolo** [vaadin/docs#3186]
Explain in a upgrade guide document the steps that an application working in 2.5 needs for working in 24.4

- [ ] Maven projects: changes in pom.xml
  - rename `hilla.version` to `vaadin.version` occurrences
  - set `vaadin.version` to `24.4.x`
  - replace `dev.hilla:hilla-bom` with `com.vaadin:vaadin-bom`
  - replace `dev.hilla:hilla` with `com.vaadin:vaadin`
  - replace `dev.hilla:hilla-spring-boot-starter` with `com.vaadin:vaadin-spring-boot-starter`
  - replace `dev.hilla:hilla- react-spring-boot-starter` with `com.vaadin:vaadin-spring-boot-starter`
  - replace `dev.hilla:hilla-maven-plugin` with `com.vaadin:vaadin-maven-plugin` 

- [ ] Gradle projects: changes in configuration files
  - rename `hillaVersion` to `vaadinVersion` occurrences in `gradle.properties`, `settings.gradle`  and `build.gradle`
  - set `hillaVersion` to `24.4.x` in `gradle.properties`
  - replace `dev.hilla:hilla-bom` with `com.vaadin:vaadin-bom` in `build.gradle`
  - if present replace `dev.hilla:hilla` with `com.vaadin:vaadin` in `build.gradle`
  - replace `dev.hilla:hilla-spring-boot-starter` with `com.vaadin:vaadin-spring-boot-starter` in `build.gradle`
  - replace `dev.hilla:hilla- react-spring-boot-starter` with `com.vaadin:vaadin-spring-boot-starter` in `build.gradle`
  - replace `dev.hilla` gradle plugin with `com.vaadin` in `buid.gradle`
  
- [ ] hilla react projects
  - remove `dev.vaadin:hilla-react` dependency since it comes already with `vaadin` artifacts
  
- [ ] hilla lit projects 
  - add `dev.vaadin:hilla` dependency 
  - optionally add exclusion for the `com.vaadin.hilla:hilla` dependency
  - configure the `reactEnabled` property to false in the `vaadin-maven-plugin`
  
- [ ] changes to `java` sources
  - replace namespace `dev.hilla` with `com.vaadin.hilla` in imports
 
- [ ] changes in `frontend` sources (`.ts` and `.tsx` files)
  - replace `@hilla/frontend` with `@vaadin/hilla-frontend`
  - replace `@hilla/form`. with `@vaadin/hilla-lit-form`
  - replace `@hilla/react-form` with `@vaadin/hilla-react-form`
  - replace `Frontend/generated/dev/hilla` with `Frontend/generated/com/vaadin/hilla`
  - replace any remaining `@hilla/` occurrence with `@vaadin/`

- [ ] special note for people testing `beta` or `rc` versions
  - add `https://maven.vaadin.com/vaadin-prereleases` as an additional repository and pluginRepository  

- [ ] Optional but recommended: move `./frontend` folder to `src/main`  
- [ ] For building the project for production you should use `./gradlew build -Pvaadin.productionMode` instead of  using the old property `hilla.productionMode`

**Comment by jojule** [comment]
GPT-4 could help us turn this to OpenRewrite recipe... 

Related: https://github.com/vaadin/hilla/issues/2089

**Comment by manolo** [comment]
Added checkbox for optionally moving frontend folder
