### ISSUE TITLE
Date Picker examples are missing few basic use cases

### ISSUE THREAD

**Issue by Haprog** [vaadin/docs#322]
Date Picker seems to be missing few examples of basic use cases that are covered in the old docs at https://vaadin.com/components/vaadin-date-picker/html-examples but are not showed on the new docs page.

1. None of the examples show how to set a `value` for the Date Picker.
    > Date Picker includes all Text Field and shared input field features.

    This kind of implies that you can set a value (if you look into those linked pages), but since Date Picker has a specific value format, there should at least be some basic example that shows how to set a value like:
    ```html
    <vaadin-date-picker value="1990-01-28"></vaadin-date-picker>
    ```
2. There are no localization examples. The old component page has https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-localization-demos with 2 demos. Not sure if we want the "Custom date parser" demo in the new docs too but at least the basic localization use case is important to have.

**Comment by web-padawan** [comment]
This was fixed by https://github.com/vaadin/docs/pull/679 especially by the "using custom functions" example.
