### ISSUE TITLE
[PiT 24.4] updating to Vaadin latest alpha causes dspublisher fail 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/docs#3328]
after updating the docs project to the latest Vaadin (24.4.0.alpha20), 
```
type: "module"
``` 
has been added to the `package.json`. [here](https://github.com/vaadin/docs/blob/next/package.json#L220)

this causes the dspublisher to fail, as they are still using commonjs modules. 

```
ReferenceError: require is not defined in ES module scope, you can use import instead
```

# reproduce
```
git@github.com:vaadin/docs.git
cd docs
npm run dspublisher:build
```

**Comment by ZheSun88** [comment]
after removing the 
```
type: "module"
```

dspublisher works, but not the docs project, with error message

```
[ERROR] Stderr: 'X [ERROR] "@vaadin/hilla-file-router/vite-plugin.js" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

```



# reproduce

```
remove the line `type: "modules"` from packge.json
mvn install -Pproduction
```

**Comment by manolo** [comment]
Related with https://github.com/vaadin/hilla/issues/2193 and https://github.com/vaadin/flow/issues/18924
