### ISSUE TITLE
TreeGrid scrollToIndex(...) documentation is totally missing

### ISSUE THREAD

**Issue by TatuLund** [vaadin/docs#3354]
The new scrollToIndex(..) with varargs should be well documented with code examples and visuals.

https://vaadin.com/docs/latest/components/tree-grid

The feature is well explained in the web-components PR, but it is not easy for Java devs to find it.

https://github.com/vaadin/web-components/pull/5428

**Comment by rolfsmeds** [comment]
This would be best to add to the `next` branch of docs that will go live with V24.4.
(If we need to backport it to older versions, we need to keep in mind that the Grid page structure has been changed significantly in the `next` branch.)

**Comment by TatuLund** [comment]
> This would be best to add to the next branch of docs that will go live with V24.4.

That is ok.

>  This is not the type of API that we would typically include in the vaadin.com/docs 

I disagree. This is a complex use case that mandates extra code example and illustration, comparable to for example setting up callback data provider etc.
