### ISSUE TITLE
Hilla configurations should be documented

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/docs#3517]
I can't find these configurations in our documentation:
```
hilla.endpoint.hot-reload.enabled=true
hilla.endpoint.hot-reload.poll-interval=5s
```

**Comment by cromoteca** [comment]
Those properties seem to be related to Hilla 2.5. If that's the case, we should make sure that newly-generated projects don't have those.

**Comment by jcgueriaud1** [comment]
It has been dropped in 24.5: https://github.com/vaadin/hilla/pull/2424

**Comment by cromoteca** [comment]
Documentation will cover the latest version, so let's close this ticket as not planned.
