### ISSUE TITLE
Document which files should be committed to git

### ISSUE THREAD

**Issue by mvysny** [vaadin/docs#353]
Please document which JS-related files go to gitignore and which ones are committed to git, and why.
For example: package.json + package-lock.json/pnpm-lock.yaml are committed in order to ensure reproducible builds.

**Comment by jouni** [comment]
Yeah, sounds reasonable. Where in the docs would you expect to find this info? Should be somewhere under "Get Started".

**Comment by mvysny** [comment]
Hmmm not sure about the placement. May not under "Getting Started" since the example project already have the files pre-committed (or git-ignored) properly, so this is not something the programmer encounters right away. Maybe some kind of "best practices" or "tips and tricks" section? I think even "Advanced Topics" is fine. The most important thing is that the documentation exists and can be found via Google :+1: (or via the docs search)

**Comment by jouni** [comment]
I suggested “Get Started” because that’s the place where we have most things that apply equally to both Flow and Fusion. Thanks for your input, in any case!

**Comment by jcgueriaud1** [comment]
In the documentation, I found this related to vcs and files.
https://vaadin.com/docs/v14/guide/upgrading/v10-13#package-management-pnpm-instead-of-bower

> package.json and pnpm-lock.yaml/package-lock.json: These files keep track of frontend packages and pin their versions. You may want to add these to version control, in particular, if you added any local package directly with pnpm/npm commands.

**Comment by tarekoraby** [comment]
Fixed. We now have https://vaadin.com/docs/latest/flow/configuration/source-control.
