### ISSUE TITLE
Wrong link on the Button component article

### ISSUE THREAD

**Issue by UjfaA** [vaadin/docs#3536]
On the Button component article in Miscellaneous Style Variants segment there is a mention of a Link (component) and it appears as a link. As displayed it looks like it should lead to the Link component (?) article, but it leads to the Button article.

[https://vaadin.com/docs/latest/components/button#miscellaneous-style-variants](https://vaadin.com/docs/latest/components/button#miscellaneous-style-variants)

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by web-padawan** [comment]
Thanks for the issue. Looking at #370 where this was added, I see the [following comment](https://github.com/vaadin/docs/blame/765b2db4ba4f2ffa61f6c335e666435fc792b97e/articles/ds/components/button/index.asciidoc#L131-L132):

```
// the link in the line above should not send the user anywhere
```

This is clearly confusing as there is no `Link` component, and the link does seem broken.

**Comment by rolfsmeds** [comment]
Ok yeah there is absolutely no reason to have the word link be an actual _link_ (nor capitalized to indicate such a component exists). Although Flow does have an Anchor component class for making links, I don't think we should link to that either.
