### ISSUE TITLE
PiT 24.5: Collaboration Kit licensing section is confusing 

### ISSUE THREAD

**Issue by manolo** [vaadin/docs#3576]
The [article](https://github.com/vaadin/docs/blob/latest/articles/tools/collaboration/going-to-production.adoc) describing how to run CE for production is not clear about licensing and versions.

It says that ' _Collaboration Kit is Now Free_ ' but it's not specified which version they need for having it free, or whether it's possible to don't pay if you are using previous versions.
In addition it's necessary to know what is are the licensing terms of the code, if it's apache or vaadin, etc

**Comment by jouni** [comment]
> it's not specified which version they need for having it free

The version is specified by the documentation version selector (i.e. V24)

> whether it's possible to don't pay if you are using previous versions

The previous documentation version explains that: https://vaadin.com/docs/v23/tools/collaboration/developing-with-ce#ce.developing.free-universal-license

There could be some confusion for users of 24.4. I’m not sure if we want to complicate the documentation for the short period of time when 24.4 is still maintained together with 24.5. We could add an admonition which we then remove once 24.4 is no longer maintained.
