### ISSUE TITLE
Broken and problematic links

### ISSUE THREAD

**Issue by johannest** [vaadin/docs#3657]
**Listing here some broken and problematic links**

**In-secure links:**
Chapter: https://vaadin.com/docs/latest/building-apps/architecture/monoliths#scalability-challenges
Link: http://www.laputan.org/mud/mud.html#BigBallOfMud

Chapter: https://vaadin.com/docs/latest/building-apps/architecture/microservices#increased-complexity
Link: http://www.laputan.org/mud/mud.html#BigBallOfMud

Chapter: https://vaadin.com/docs/latest/building-apps/project-structure/single-module
Link: http://www.laputan.org/mud/mud.html#BigBallOfMud

**Broken links:**
Chapter: https://vaadin.com/docs/latest/building-apps/project-structure#jar-file-packaging
Links:
- https://docs.spring.io/spring-boot/reference/packaging/container-images/index.html:  (remove : from the end)
- https://github.com/kohsuke/winsw: (remove : from the end)

Chapter: https://vaadin.com/docs/latest/building-apps/project-structure#war-file-packaging
All links ending with : which breaks those

Chapter: https://vaadin.com/docs/latest/building-apps/project-structure/single-module
Link: https://docs.spring.io/spring-boot/maven-plugin: (remove : from the end)
Link: https://vaadin.com/docs/latest/building-apps/project-structure/%7Barticles/flow/configuration/development-mode

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by peholmst** [comment]
I'll take care of these right away.
