### ISSUE TITLE
Wrong text fragment styling in "data provider"?

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/docs#369]
Page: https://vaadin.com/docs/latest/flow/binding-data/data-provider/#filtering-with-lazy-data-binding
Issue: Text fragment is shown as monotyped text with grey background, but I assume it shall be normal text?

![image](https://user-images.githubusercontent.com/36725474/114846348-e5e09a00-9ddc-11eb-8bca-0a9c8b459cea.png)

**Comment by jouni** [comment]
Thanks! Fixed in f71adf0220676c03ef888bf9b8b2238bb389f0e0
