### ISSUE TITLE
Mention the need to explicitly set a sort property with lazy dataproviders and a renderer

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#385]
If you have a lazy-loading DataProvider and a column with a Renderer which gets its data from a bean property via a String property name, it should be mentioned eg. in https://vaadin.com/docs/latest/components/grid/flow/#using-a-sort-property-name that an explicit sort property name is mandatory to get the necessary sorting info to the backend.

**Comment by Avec112** [comment]
sort not working
`grid.addColumn(new LocalDateTimeRenderer<>(MyClass::getDateTime, DATE_TIME_FORMAT), "dateTime"); `

sort working
`grid.addColumn(new LocalDateTimeRenderer<>(MyClass::getDateTime, DATE_TIME_FORMAT)).setSortProperty("dateTime");`
