### ISSUE TITLE
The Style section of the flow tutorial is missing a step to first apply the channel-list custom style to the LobbyView class

### ISSUE THREAD

**Issue by dogeared** [vaadin/docs#3892]
In the Styles section of the Flow tutorial, there is a small omission with regard to setting the `channel-list`  style in the `VirtualList` component for the channels. 

If you follow the tutorial exactly as-is, the channel list will be rendered differently than shown in the screenshot in the tutorial as the `channel-list` class is never applied.

This is fixed in PR: #3891 
---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by peholmst** [comment]
Thank you! The fix has been merged.
