### ISSUE TITLE
Describe syncId and clientId and overall client-server messaging

### ISSUE THREAD

**Issue by mshabarov** [vaadin/docs#3911]
**Tell us about your request**

To describe how client-server messaging works and what are `syncId` and `clientId` for.
The only snippet about these Ids are in this article https://vaadin.com/blog/performance-testing-a-vaadin-application-part-2-application-internals. 

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by TatuLund** [comment]
Related to: https://github.com/vaadin/docs/issues/3822
