### ISSUE TITLE
Document DatePicker fallback parser feature

### ISSUE THREAD

**Issue by vursen** [vaadin/docs#3930]
Explain how and when to use the [DatePicker fallback parser](https://github.com/vaadin/flow-components/issues/2466), including a live example.

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by rolfsmeds** [comment]
Let's add a new "Server-Side Parsing in Flow" top-level section to the Date Formats tab, with a live sample of the feature.
