### ISSUE TITLE
Flow: component theming outdated (V14.6.alpha, V19)

### ISSUE THREAD

**Issue by anezthes** [vaadin/docs#395]
The old way required explicit importing and using `themeFor`.
```
@CssImport(value = "./styles/components/button.css", themeFor = "vaadin-button")
```

The new way only requires you name the stylesheet correctly and place it in the right folder.
```
my-app/frontend/themes/myapp/components/vaadin-button.css (exists)
```

AFAIK there's no mention of this #ffs. :D

**Comment by jouni** [comment]
Yes, styling and theming docs in the v14 branch are a mix of old and new at the moment. We need to clean it up.

> AFAIK there's no mention of this #ffs. :D

It is documented here: https://vaadin.com/docs/v14/flow/styling/custom-theme/#vaadin-component-styles

**Comment by jouni** [comment]
The theming and styling docs have been partly rewritten and restructured since. @rolfsmeds is also working on a full rewrite. Closing as resolved.
