### ISSUE TITLE
Update components type definitions documentation for V20

### ISSUE THREAD

**Issue by web-padawan** [vaadin/docs#414]
Here is the article: https://vaadin.com/docs/latest/fusion/advanced/components-definitions

Things that need to be done:

1. change "Custom Events" to mention all components and use `Since Vaadin 20` badge
2. update the examples to use type definitions with `Event` suffix instead of the typings that are deprecated (the new typings are available since `20.0.0.alpha8` - see https://github.com/vaadin/web-components/pull/234 and https://github.com/vaadin/web-components/pull/240)

We also need to figure out a better place for this article, probably not under "Advanced" section.

**Comment by jouni** [comment]
I checked the page, and it seems that at least the `Event` suffix is shown. There’s still a `Since V19` badge there, but I think that’s a non-issue, as both V19 and V20 are already unsupported.
