### ISSUE TITLE
Please document on how to add SessionInitListener

### ISSUE THREAD

**Issue by mvysny** [vaadin/docs#417]
The page https://vaadin.com/docs/v14/flow/advanced/tutorial-service-init-listener is awesome but it could go a bit further, to document on how to initialize a session:

```java
public class ApplicationServiceInitListener
        implements VaadinServiceInitListener {

    @Override
    public void serviceInit(ServiceInitEvent event) {
         // ...
        event.getSource().addSessionInitListener(e -> {
            // init the session
        });
    }

}
```

**Comment by tarekoraby** [comment]
This page also needs improving as it doesn't mention that in Spring projects one can register the `VaadinServiceInitListener` using `@Bean`. Once improved, it would also be good to link this page from the [Application-lifecycle](https://vaadin.com/docs/latest/flow/advanced/application-lifecycle) chapter.

**Comment by tarekoraby** [comment]
v14 and vLatest branches now have this documented:

- https://vaadin.com/docs/v14/flow/advanced/tutorial-ui-init-listener
- https://vaadin.com/docs/latest/flow/advanced/session-and-ui-init-listener
