### ISSUE TITLE
lumoImports property of theme.json is not documented

### ISSUE THREAD

**Issue by Haprog** [vaadin/docs#433]
The `lumoImports` property should probably be documented at https://vaadin.com/docs/latest/ds/customization/custom-theme-configuration

For example one use case for this feature is to import Lumo `badge` styles to be able to use Badge. After the docs for `lumoImports` have been added, the [Badge](https://vaadin.com/docs/latest/ds/components/badge) page should also be updated to link to it so the users can find out how to import the badge styles which is now not covered on the Badge page.

Implementation source code of `lumoImports` (for reference): https://github.com/vaadin/flow/search?q=lumoImports&type=code

Some related discussion in internal Slack: https://vaadin.slack.com/archives/CQUQWJ4KU/p1616759094157900

**Comment by web-padawan** [comment]
There are some mentions now in the following pages:

- https://vaadin.com/docs/latest/components/badge
- https://vaadin.com/docs/latest/styling/lumo/utility-classes

However, the original page still lacks mention of `lumoImports`.

**Comment by web-padawan** [comment]
The `lumoImports` documentation was added in #2071 and it's now under a dedicated [Theme Configuration](https://vaadin.com/docs/latest/styling/application-theme#theme-configuration) section. Closing.
