### ISSUE TITLE
No "SecurityConfig.java" on https://vaadin.com/docs/latest/fusion/security/spring-login

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/docs#463]
![image](https://user-images.githubusercontent.com/5602528/118259803-40dbde80-b4ba-11eb-863d-0c5998ab6fe8.png)

Note, there is `SecurityConfigDemo.java`, but it has `setLoginView`, and not `setLogin` mentioned in documentation

**Comment by jouni** [comment]
Fixed in https://github.com/vaadin/docs/commit/a4e4ff8ff0d25278c1b5fe6414fa8f8893202567 (latest) and https://github.com/vaadin/docs/commit/a770921aaa73bf467ba36468d60361b5f2ae0f9e (v20).
