### ISSUE TITLE
Reconsider usage of external-link icon

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#478]
The docs include many links with the external-link icon, like the following
![image](https://user-images.githubusercontent.com/42799254/118771086-c7156d80-b88a-11eb-8d1b-d1353dae1976.png)

 To me, this conveys that the link will open in a new browser tab. However, those links actually replace the current view, which is probably confusing for many users. Thus, please reconsider the usage of this icon by either removing it or, if appropriate, making those links actually open in a new browser tab.

**Comment by jouni** [comment]
Closed in https://github.com/vaadin/docs-app/commit/6c7d3137dcb308af8292667a2e3631bbbe9fd66b
