### ISSUE TITLE
The demos at vaadin.com are confusing as they contain "magic methods"

### ISSUE THREAD

**Issue by mstahv** [vaadin/docs#482]
The component demo at https://vaadin.com/components/vaadin-ordered-layout/java-examples/verticallayout contains a lot of methods that are not defined for end users. Those reading the documentation should have access to those, so that examples can be easily copy-pasted to developers own IDE.

**Comment by web-padawan** [comment]
Moved this from web components repository as the examples are now developed here.

**Comment by rolfsmeds** [comment]
This has been resolved in the new docs.
