### ISSUE TITLE
Security page doesn't give the user/password

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/docs#484]
I tried the new security for Vaadin 20.
after copy/pasting the documentation https://hilla.dev/docs/lit/guides/security/spring-login

```java
@Override
  protected void configure(AuthenticationManagerBuilder auth) throws Exception {
    // Configure users and roles in memory
    auth.inMemoryAuthentication()
        .withUser("user").password("{noop}user").roles("USER")
        .and()
        .withUser("admin").password("{noop}admin").roles("ADMIN", "USER");
  }
```
I tried to login with admin and {noop}admin and it fails. Then I removed {noop} and it also fails.
Should we add something in the documentation to explain what is {noop} or how to login?

Proposal solution:
- maybe extract "{noop}" to a constant NO_ENCRYPTION (edited) 
- Maybe NO_HASHING instead so that we wouldn't give the wrong impression (encryption is supposed to be reversible whereas hashing isn't, even though Spring Security is also using the same confusing terminology)
- add a comment in the code or something in the doc for more explanation

**Comment by cromoteca** [comment]
Removing `{noop}` when signing in is the right thing to do: that prefix triggers Spring's `NoOpPasswordEncoder`. I don't know why it didn't work for you.

**Comment by jouni** [comment]
I assume this should’ve been close by #2166
