### ISSUE TITLE
HorizontalLayout with spacing, margin and expand is too wide

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/docs#485]
```java
HorizontalLayout formLayout = new HorizontalLayout();
formLayout.setWidth("100%");
formLayout.setMargin(true);
formLayout.setSpacing(true);
TextField taskField = new TextField();
Button addButton = new Button("Add");
formLayout.add(taskField, addButton);
formLayout.expand(taskField);
```

Leads to the layout being approx margin + padding too wide: 

![screen shot 2018-03-07 at 3 17 29 pm](https://user-images.githubusercontent.com/883698/37123947-12eaf2ac-221b-11e8-8c67-3bda0a939d9f.png)

**Comment by web-padawan** [comment]
Moved this to docs repo as the resolution seems to be that we need a better example.

**Comment by rolfsmeds** [comment]
Closing as outdated
