### ISSUE TITLE
Document importing projects to VSCode

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#489]
Docs currently have instructions on how to import a Vaadin project to Eclipse, Intellij, and NetBeans (https://vaadin.com/docs/latest/guide/importing). Similar instructions are needed for VSCode (which is especially important as Vaadin promotes it elsewhere as the IDE of choice for Fusion projects).

**Comment by gilberto-torrezan** [comment]
Related to https://github.com/vaadin/docs/issues/430

**Comment by HerbertsVaadin** [comment]
@magi42 Is it okay for me to work on this?

**Comment by magi42** [comment]
Go ahead, it would be good to have that. Yeah VS Code instructions are missing even though it's recommended for TS.

**Comment by magi42** [comment]
Oddly, we have the IDE recommended table here https://vaadin.com/docs/latest/guide/contributing-docs/editing-tools but not in the Installing or Importing articles.
