### ISSUE TITLE
Add example how to use grid with the dataProvider

### ISSUE THREAD

**Issue by ghost** [vaadin/docs#513]
I cannot find any example on how to realize an infinite (remote) scrolling with the new dataprovider component.
I found only old examples, here and there, and the closest one provided with the grid is too simple to reach this important goal. I mean: surely it's not only me to need such a behavior...
I tried modifying the examples, but I get 'repeating' tiles (every group of rows is always the same!) and I don't know how to implement a proper 'stop' condition, when reaching the end of the dataset.
I would like a solution where I don't have to ask explicitly the size of the dataset upfront...
Thank you!

**Comment by vursen** [comment]
Closed per https://github.com/vaadin/docs/pull/2202.
