### ISSUE TITLE
Clarify that custom-theming can work with custom components

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#518]
The custom-theme doc page for [v14 ](https://vaadin.com/docs/v14/flow/styling/custom-theme) and [latest ](https://vaadin.com/docs/v20/ds/customization/custom-theme) mostly suggest that this mechanism can only be applied to Vaadin standard components. Thus, the fact that this mechanism can also work with custom Polymer or Lit components is not sufficiently highlighted (it is mentioned in passing in a couple of lines). 

For clarity and preciseness, consider using "Components" instead of the "Vaadin Components" that is currently used. While doing so, it could be clarified (in a prominent way) at the beginning of the chapter that "Component" here implies a component that implements ThemableMixin, noting that the latter is true for all Vaadin components, and that it can be made true for any custom component (linking to instructions for implementing ThemeableMixin with custom components, see #517).

**Comment by jouni** [comment]
I think this issue is already outdated, as we are moving towards ::part-based styling.
