### ISSUE TITLE
Chapter "Integration > Spring" should provide an example for required Spring Security settings

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/docs#529]
The documentation provides a good start to connect Spring and Vaadin, but one aspect, that many customers are using is missing: Spring Security. We have a tutorial for that, where also an example configuration is provided, but it should be part of the official documentation, since someone using Spring Sec for a long time might not check a tutorial but the docs.

Therefore the docs should provide an overview of all needed settings for Spring Security, so that no other source is needed then the docs to connect Vaadin and Spring Security. It should also provide a link to the tutorial, like "If you want to have a detailed step by step description, check our tutorial" or similar.

**Comment by tarekoraby** [comment]
We have now a dedicated Vaadin + Spring Security helpers and corresponding page in the docs: https://vaadin.com/docs/latest/flow/integrations/spring/view-based-access-control.
