### ISSUE TITLE
Add indication of non-vLatest docs

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#543]
When one is on a non-vLatest part of the docs, it would be useful to have a noticeable indication (perhaps a top banner ) reminding the reader that they are viewing the non-vLatest docs (and perhaps linking them to the vLatest part). This would be particularly useful for users who are not very familiar with Vaadin versions, and who might reach a certain part of the docs through a google search.

**Comment by tarekoraby** [comment]
But wouldn't it be useful to add it to v7, 8, 10, and 14?

**Comment by jouni** [comment]
Yeah, sure. I guess I got hung up on the "LTS" term in the issue title and description. Should probably be more about "non-latest" than "non-LTS".

**Comment by jouni** [comment]
There are now banners on all non-latest docs versions.
