### ISSUE TITLE
Remove mention of fixed bug

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#605]
The Designer [tutorial ](https://vaadin.com/docs/v20/tools/designer/getting-started/connecting-your-contact-form-to-java) mentions a [bug](https://github.com/vaadin/flow/issues/8256) with `setVisible(false)` which should be now fixed (at least for vLATEST). The mention of this bug (and its workaround) should be thus removed from the tutorial.

**Comment by jouni** [comment]
Go ahead and submit a PR 🤗

**Comment by jouni** [comment]
Fixed in latest (5106a5e9d82cbe44a076b756e511af866bce36d7)
