### ISSUE TITLE
Remove Installing chapter from Latest

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#650]
The [Installing chapter ](https://vaadin.com/docs/latest/guide/install) in the Get-Started guide of latest mainly mentions Java and Maven installations as prerequisites. However, Maven installation is no longer a prerequisite since Maven wrapper is now shipped with the downloaded starters. This leaves Java as the only real prerequisite to run a Vaadin app, but IMO that doesn't warrant a full chapter in the docs as it's very likely that the overwhelming majority of docs' visitors already have Java installed. 

Thus consider removing the Installing chapter altogether as it would simplify the journey of new evaluators. (It would suffice to add a link to amazon Correto at the beginning of the following chapter).

**Comment by jouni** [comment]
@tarekoraby, is this issue still up to date?

**Comment by tarekoraby** [comment]
Should be fixed by #919.
