### ISSUE TITLE
Broken Design System Publisher link 

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#664]
The Design System Publisher link at https://vaadin.com/docs/v14/tools/overview is broken

**Comment by rolfsmeds** [comment]
URL seems to be missing one level of `../`

**Comment by jouni** [comment]
Not sure why the link doesn't work. Need to debug this locally. I mean, similar links (across docs versions) seem to work fine in https://vaadin.com/docs/latest/guide/upgrading/#earlier-versions

**Comment by jouni** [comment]
Seems to be working now.
