### ISSUE TITLE
Disable autofocus in Login samples to prevent erratic scrolling

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/docs#677]
As mentioned in https://github.com/vaadin/vaadin-login/issues/121#issuecomment-888206239, the default autofocus in Login component makes[ the docs page](https://vaadin.com/docs/latest/ds/components/login) virtually unusable since the samples keep stealing focus.

`no-autofocus` flag shoud be applied to all samples, together with a comment explaining that it's just there for the docs

**Comment by jouni** [comment]
I started working on this, but now I can't find the Flow component API, `setNoAutofocus(boolean)`. Seems like that hasn’t been added.
