### ISSUE TITLE
Remove all PageConfigurator references from docs

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/docs#678]
`PageConfigurator` has logical problems and bugs, see e.g. https://github.com/vaadin/flow/issues/11518.

In the master branch there is `AppShellConfigurator` which should be used instead.
There is also proper way of doing things via `BootstrapListener`.
Every mention of `PageConfigurator`  should be replaced via `AppShellConfigurator` or `BootstrapListener`.

**Comment by pleku** [comment]
The ticket description is wrong one - the references should not be removed, but updated with ways to achieve the same things without using `PageConfigurator`. If there is no way to do the same thing with API provided by `BootstrapListener` / `AppShellConfigurator`, then it probably should be ticketized.

**Comment by jouni** [comment]
The only reference to `PageConfigurator`, which doesn't include a disclaimer that it is deprecated, is in https://vaadin.com/docs/latest/advanced/loading-indicator, and it looks like the code example has already been updated, but the lead-in text wasn't updated accordingly.

**Comment by jouni** [comment]
Removed the mention in 243fdd1b0f56371a6355d2f4fabfb73616818b74
