### ISSUE TITLE
Update Fusion routing documentation for new starter projects

### ISSUE THREAD

**Issue by magi42** [vaadin/docs#700]
The Fusion apps generated by start.vaadin.com now have a separate `routes.ts` for routing, and `index.ts` has changed significantly. All of the current routing examples still use the old structure. The elements in the two files need to be explained in detail at least somewhere.

At least:
- [ ] [Fusion Application Architecture](https://vaadin.com/docs/latest/fusion/application/basics/#application-architecture) as well as the Basic Routing sub-section
- [ ] The entire [Fusion Routing and Navigation](https://vaadin.com/docs/latest/fusion/routing/overview) section
- [ ] [Fusion Quick Start Tutorial](https://vaadin.com/docs/latest/fusion/tutorials/quick-start-tutorial)
- [ ] There's also one in the [Flow Basic Routing](https://vaadin.com/docs/latest/flow/application/routing-navigation) article

**Comment by jouni** [comment]
These seem to have been resolved already.
