### ISSUE TITLE
VaadinServletConfiguration is deprecated and will be removed in 6.0 Flow. The docs should be updated.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/docs#73]
The replacement for `VaadinServletConfiguration` should be described since it's deprecated and is going to be removed in
`6.0`.

**Comment by jouni** [comment]
Any news on this? Tagging @pleku as well.

**Comment by mshabarov** [comment]
This issue looks a bit obsolete, since there are no deprecated mentions in the latest branches.
