### ISSUE TITLE
Vaadin Fusion now does not support OAUTH2 Authentication using spring-boot-starter-oauth2-client

### ISSUE THREAD

**Issue by drdoug007** [vaadin/docs#778]
After upgrading the tutorial https://vaadin.com/learn/tutorials/google-login to Vaadin 21, the application gets the following error.
<img width="608" alt="Screen Shot 2021-09-30 at 12 05 23" src="https://user-images.githubusercontent.com/11632050/135391997-0b2a235b-8b03-41b4-8d52-3a3cea95a45f.png">
 
The tutorial needs to be updated for the current version of Vaadin.

**Comment by drdoug007** [comment]
Updated Vaadin to 21.0.2 and Spring Boot to 2.5.4
<img width="644" alt="Screen Shot 2021-09-30 at 12 30 44" src="https://user-images.githubusercontent.com/11632050/135392948-be07cd68-806b-42cd-bf0b-75bd7ace7cd5.png">

In SecurityConfiguration.java changed ServletHelper to HandlerHelper
<img width="1241" alt="Screen Shot 2021-09-30 at 12 33 20" src="https://user-images.githubusercontent.com/11632050/135393302-bbd1787a-ea10-414b-810f-59efbc0e82e7.png">

**Comment by drdoug007** [comment]
Here is the exception in the logs
<img width="1447" alt="Screen Shot 2021-09-30 at 12 54 56" src="https://user-images.githubusercontent.com/11632050/135395447-018aac42-14ea-4eb4-b08e-978eb8fd2c20.png">

**Comment by drdoug007** [comment]
Update: It goes to the google login screen if you click on the refresh button on the error screen

**Comment by magi42** [comment]
The tutorial is for V14 and should not be updated. Such Spring documentation should probably go somewhere under Spring integration in Docs in https://vaadin.com/docs/latest/flow/integrations/spring/overview . We'll see who could migrate the article. Would be nice to add a link there to the tutorial.

The docs article should have a docs tone of voice, and not be a tutorial.

**Comment by magi42** [comment]
Ah, was this this about Fusion? The V14 article is for Flow (no Fusion back then). For Fusion, it maybe should go under Security https://vaadin.com/docs/latest/fusion/security/overview .

**Comment by drdoug007** [comment]
I was able to get it working by changing the Anchor to a Button and executing JavaScript to change the location
 
```
String script="window.location.href = $0";
Button googleLoginButton = new Button("Login with Google");
googleLoginButton.addClickListener(a-> UI.getCurrent().getPage().executeJs(script, URL));
```

**Comment by tarekoraby** [comment]
There is an updated oauth2 tutorial for v23 here: https://vaadin.com/blog/oauth-2-and-google-sign-in-for-a-vaadin-application, and the source code is available here: https://github.com/vaadin/vaadin-oauth-example.
