### ISSUE TITLE
Document binding of sub-properties

### ISSUE THREAD

**Issue by SebastianDietrich** [vaadin/docs#788]
When it comes to binding of sub-properties (i.e. properties of a referenced object, e.g. properties of an embedded `@Embeddable`) this is poorly documented.
I've only found the following:

- The javadoc of [Binder](https://vaadin.com/api/platform/22.0.0.alpha6/com/vaadin/flow/data/binder/Binder.html#Binder-java.lang.Class-boolean-) and [BeanValidationBinder](https://vaadin.com/api/platform/22.0.0.alpha6/com/vaadin/flow/data/binder/BeanValidationBinder.html#BeanValidationBinder-java.lang.Class-boolean-) show that it is possible to bind sub-properties (if the parameter scanNestedDefinitions is set to true)
- In the [latest documentation on binding](https://vaadin.com/docs/latest/flow/binding-data/components-binder-beans) the first example has "address.street" but no further info. Interestingly in this example the Binders constructor is not called with scanNestedDefinitions = true - so this example is somehow misleading.

And unfortunately there is the following [info in the old forum](https://vaadin.com/forum/thread/17017417/binder-and-embedded-jpa-valueobjects) which basically says that binding of sub-properties does not work at all.

So please update the documentation:

- change the first example in [the documentation on binding](https://vaadin.com/docs/latest/flow/binding-data/components-binder-beans) to not bind a sub-property or change the constructors call to be called with scanNestedDefinitions = true
- add a short explanation there and as well when [explaining @PropertyId](https://vaadin.com/docs/latest/flow/binding-data/components-binder-beans/#specifying-property-names) how accessing sub-properties work
- if binding to sub-properties without `@PropertyId` is as well possible when using [automatic data binding](https://vaadin.com/docs/latest/flow/binding-data/components-binder-beans/#automatic-data-binding) please explain how it works there as well. I would expect it to somehow work when having instantiated the Binder with scanNestedDefinitions = true

**Comment by gtzluis** [comment]
a

**Comment by mcollovati** [comment]
When `Binder` is created giving a class, it internally uses a `BeanPropertySet` to determine existing properties.
With `scanNestedDefinitions = true`, all properties are eagerly detected.
If `scanNestedDefinitions` is false, the nested properties are lazily detected when the property is bound to a field.

In the documentation example, when invoking `binder.bind(streetAddressField, "address.street");`, the property is not found, but `Binder`, or better `BeanPropertySet`, detects that it may be a nested and tries to load the definition of the nested property.

**Comment by mcollovati** [comment]
Automatic binding to nested properties without a `@PropertyId` is not supported because the field name is used to match the property of the bean.
`BeanPropertySet` references nested fields with the dot separated syntax (e.g. `address.street`) but of course it is not possible to define a Java field name containing a dot.
Using `@PropertyId` is the way to go for nested properties.

**Comment by jouni** [comment]
Possibly a duplicate: #1966
