### ISSUE TITLE
Documentation : Lacking use cases for LoginForm and LoginOverlay

### ISSUE THREAD

**Issue by anasmi** [vaadin/docs#80]
There is not much information about differences between `LoginForm` and `LoginOverlay`, which imposes the question, which one should be used under what circumstances. Also, it's not opened anywhere what does overlay exactly means (Nor I found any official definition, so it would be nice if we could open it on our site)
Encouraged by this discussion on SO: https://stackoverflow.com/questions/59482312/loginform-versus-loginoverlay-in-vaadin-14/

**Comment by web-padawan** [comment]
Moved to the docs repository. Let's take this into account when creating demos for these components.

**Comment by jouni** [comment]
The [updated documentation content](https://docs.google.com/document/d/1BDfG4E-DOFDNrfsJ3FDWNS4FlovDNmalHfhD8hgNXGE/edit) has been written. Feel free to take a look and provide feedback either in the document or here.

**Comment by web-padawan** [comment]
Overall LGTM. Yes, let's close this issue as it's quite outdated. We can submit another issue if new docs are still unclear.

BTW, I checked the original question and there is a comment there:

> So what is an “overlay” in Vaadin? When/why would I want to use an overlay?

IMO this deserves another article describing how overlays work, including modality. But that's a separate topic.

**Comment by kolle1986** [comment]
Still lacking. How can I target [part="backdrop"] in vaadin-login-overlay-wrapper from extended LoginOverlay.java in flow?

**Comment by jouni** [comment]
@kolle1986, thanks for the feedback. Component styling documentation is still lacking in many ways, and is something we want to improve in the future.

For your specific question: it looks like you need to use `vaadin-login-overlay-wrapper ` as the name of the component. So the following should work:

`frontend/themes/my-theme/components/vaadin-login-overlay-wrapper.css`:
```css
[part="backdrop"] {
  ...
}
```

And if you want to have some specific styles for the extended component only, you need to add a theme variant for the component (`login.getThemeList().add("my-variant")`), and then target that in your CSS:

```css
:host([theme~="my-variant"]) [part="backdrop"] {
  ...
}
```

**Comment by kolle1986** [comment]
Alright, thanks @jouni, I will try as you suggested. One related question is referencing image file from css file. 
I have image file on path ../src/main/resources/META-INF/resources/images/background.jpg but can't achieve to set it as background for this login overlay via `background-image: url("./images/background.jpg"); ` Followed https://vaadin.com/docs/latest/flow/advanced/loading-resources/#resource-cheat-sheet but still no luck. 
Is it something maybe withe resources mapping in spring boot vaadin 21 project? It is working when try to reference image from java code `add(new Image("images/logo.png", "A plane"));`

**Comment by jouni** [comment]
I’m not aware of anything that could prevent using JPG or SVG images. Does some other format work?

**Comment by kolle1986** [comment]
It's very strange, I just converted image to png and it works. Never mind, thanks anyway I will try to figure out what is the problem.
