### ISSUE TITLE
"Open in a new tab" button not working for Java only examples

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/docs#810]
Cannot confirm if that happens in all cases and I can't think of any other examples implemented only in Java, but clicking on the "Open in a new tab" button on the examples at the [Inline Editing (Java Only) for Grid](https://vaadin.com/docs/latest/ds/components/grid#inline-editing-java-only) leads to a blank box.

**Comment by jouni** [comment]
My assumption is that some front-end imports are missing from those examples somehow.
