### ISSUE TITLE
vaadin.whitelisted-packages property is missing in the docs

### ISSUE THREAD

**Issue by simasch** [vaadin/docs#822]
Setting the packages in the property vaadin.whitelisted-packages can massively shorten the start time of a Vaadin Spring Boot app!

i.e.
`vaadin.whitelisted-packages=ch.tosca,com.github.appreciated`

Please add this feature to the documentation.

**Comment by tarekoraby** [comment]
whitelisted-packages and blacklisted-packages are now mentioned at https://vaadin.com/docs/latest/flow/integrations/spring/configuration/#configure-the-scanning-of-packages.
