### ISSUE TITLE
Starting dev server hangs on `npm install` phase

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/docs#881]
This started happening recently and I can't figure out what's causing this behavior. 

When running `mvn`, the builds hangs at the `npm install` phase with the message `idealTree:docs: sill idealTree buildDeps`. I have waited for several minutes and no progress after that. Trying to manually run `npm install` doesn't change the issue, but surprisingly if I run `npm install --verbose`, it install all the dependencies correctly.

Have tried on `latest` and `14.8` branches and could see the same behavior.

- npm version: 8.1.2
- node version: v14.15.3

**Comment by jouni** [comment]
Running `mvn spring-boot:run` worked fine for me on `latest`. Node 16.13.0, npm 8.1.3.

**Comment by jouni** [comment]
Please comment/reopen if you still have this issue.
