### ISSUE TITLE
Improve grid's documentation to include a section for configuring column.

### ISSUE THREAD

**Issue by hdamr** [vaadin/docs#884]
This topic is covered in the [old](https://vaadin.com/components/vaadin-grid/java-examples/configuring-columns) docs, it needs to be added to new site too.

Related: https://github.com/vaadin/flow-components/issues/1618

**Comment by jouni** [comment]
I assume these docs would cover the same things: https://vaadin.com/docs/latest/components/grid/flow/#configuring-columns

The Grid docs could still use a lot of improvements, but I consider this issue resolved.
