### ISSUE TITLE
Clear button not clearly documented

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin/docs#887]
### Describe your motivation

Many of the input components support showing a clear button in field, but the feature is not documented in many of the component pages.

### Describe the solution you'd like

I would like to see the feature documented on component pages. In addition a list of components that support clear button could be under [Input Fields](https://vaadin.com/docs/latest/ds/components/input-fields) page.

**Comment by web-padawan** [comment]
Moved to docs repo as the issue belongs here.

**Comment by rolfsmeds** [comment]
It is actually described on the Text Field page to which all text-input component pages link.

(The bigger question of whether and how all that content should be duplicated for each component separately could be discussed in a separate issue).

**Comment by web-padawan** [comment]
I'd say we should add examples for DatePicker, ComboBox, TimePicker and MultiSelectComboBox:

1. Having a dedicated live demo reduces the need for jumping to another page for such components,
2. Some of these used to include `vaadin-text-field` internally, but they no longer do that since V22.

**Comment by web-padawan** [comment]
This was addressed by #2337 where "Basic features" section was added for all input field components.
