### ISSUE TITLE
Add non-image example for resources in Resource Cheat Sheet

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#920]
Resource Cheat Sheet: https://vaadin.com/docs/latest/flow/advanced/loading-resources/#resource-cheat-sheet

Apparently, non-image resources (.pdf, .rtf files and so one) require a forward slash in order to be loaded correctly; for example, `VaadinServlet.getCurrent().getServletContext().getResource("docs/foo.pdf");` does not work, but  `VaadinServlet.getCurrent().getServletContext().getResource("/docs/foo.pdf");` does. This is opposed to Images, where a forward slash is not needed, as in the current cheat sheet's example:
<html>
<body>

new Image("img/flower.jpg", "A flower") | /src/main/webapp/img/flower.jpg
-- | --

</body>
</html>
There could be a separate row for non-image resources to point this out.

**Comment by mcollovati** [comment]
I think the main difference is that with `Image` the resource is resolved as a consequence of an HTTP request, handled by `StaticFileServer` or by the servlet container.

The `ServletContext.getResource` method states that `The path must begin with a "/" and is interpreted as relative to the current context root.`

Anyway, it's a good idea to document how to handle resource directly on the UI code.
We can add an example for an `Anchor` pointing to a pdf using:
* string path + `route-ignore`
* StreamResource + resource accessed through servlet context
* StreamResource + resource accessed through `Class` or `ClassLoader`

**Comment by mcollovati** [comment]
Weird enough, tomcat by default seems not to respect the specification.
It adds the `/` in front of the path if missing.
To change the behavior, one should set either `org.apache.catalina.core.ApplicationContext.GET_RESOURCE_REQUIRE_SLASH` or `org.apache.catalina.STRICT_SERVLET_COMPLIANCE` system properties to true.

At least, this is what happens with embedded tomcat 9.x.
I have not yet tried with a standalone tomcat distribution
