### ISSUE TITLE
[dialog] docs: clarify default behavior for Dialog with "no-padding" theme + draggable enabled

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/docs#934]
Add a note on the docs page, probably on the "Removing the Padding" section, that by default there's no draggable area in a Dialog with `no-padding` theme set even when `draggable` is enabled and that the user must assign a custom drag handle by adding a CSS class named `draggable` to the desired element.

**Comment by jouni** [comment]
I believe the dragging conditions are quite well explained in https://vaadin.com/docs/latest/components/dialog/#draggable

**Comment by jouni** [comment]
Diego, if you still think there’s something to clarify, please add comment.
