### ISSUE TITLE
Document the `items` select API in V23

### ISSUE THREAD

**Issue by vursen** [vaadin/docs#965]
The `items` API for the select component has been added in https://github.com/vaadin/web-components/issues/501 and is planned to be shipped in V23. That means this feature should be documented as one of the ways to render select options along with the DOM API.

Here is an example of how the `items` property can be used:

```html
 <vaadin-select id="select"></vaadin-select>

 <script>
 const select = document.querySelector('#select');
 select.items = [
   { label: 'Most recent first', value: 'recent' },
   { component: 'hr' },
   { label: 'Rating: low to high', value: 'rating-asc' },
   { label: 'Rating: high to low', value: 'rating-desc' },
   { component: 'hr' },
   { label: 'Price: low to high', value: 'price-asc', disabled: true },
   { label: 'Price: high to low', value: 'price-desc', disabled: true }
 ];
 </script>
```

**Comment by vursen** [comment]
Currently, all the existing examples use the DOM API when providing possible select options. The new `items` property feature can be documented in two ways:

- Promote the `items` API as the primary way to provide possible select options and mention the DOM API as an alternative.
- Keep using the DOM API for most of the examples and mention the `items` API as an alternative.

**Comment by sissbruecker** [comment]
I would also vote for (1), the items API should be the default to use the examples. There are two demos, [custom item label](https://vaadin.com/docs/latest/ds/components/select/#custom-item-label), and [custom item presentation](https://vaadin.com/docs/latest/ds/components/select/#custom-item-presentation), for which we would need to use the renderer API, so would have demos for both APIs in our docs.

**Comment by danielvanmil** [comment]
Is there a way to select the V22 doc as now the selected V22 doc for vaadin-select describes an example of the items property of V23 which is not yet supported in V22? (or generate the doc for V22 somehow?)

**Comment by jouni** [comment]
Hi! I didn't realize before that the `items` property was also backported to V14, so you can't check the examples from there either.

At least for the moment, you can still access V21 docs, which shows the previous examples: https://vaadin.com/docs/v21/ds/components/select

Another alternative is to browse the source code here in the repo: https://github.com/vaadin/docs/tree/708cd668a715ce32a687f775bfddaf7fa22b4e68/frontend/demo/component/select

**Comment by danielvanmil** [comment]
Thanks @jouni. But it is still strange the documentation (with examples etc.) is only available for the "lastest" version (at this moment an alpha version). This is confusing. Any plans to fix this and just show the doc of the latest stable on the website?

It would also nice to tag the doc repo so we can just run the doc locally with the correct version?

**Comment by jouni** [comment]
Yeah, I admit we were too eager with this update, and should’ve waiting at least until there’s a beta release for v23.

We have discussed moving to a model where in addition to `latest` we would have a `next` branch. Not sure if we’ll revert the changes in latest anymore.

Tags would be convenient. I’ll see if we could get those automated.

Running the docs locally is a bit complicated, as we are using our commercial Design System Publisher tool for building the docs, and it requires a license to use (Prime subscription).

**Comment by jouni** [comment]
Or perhaps better than reverting would be to offer two TS examples instead.

**Comment by jouni** [comment]
Turns out we (Vaadin) promises to support v22 for one year, so a dedicated docs branch for it is in order, which has now been created. The Select TS examples are reverted back to the previous versions at the same time. 

The V22 docs are not yet deployed, but will appear next week at latest.
