### ISSUE TITLE
Documentation how to mock UI.getCurrent() and similar in tests

### ISSUE THREAD

**Issue by mvysny** [vaadin/docs#981]
It would be helpful for Vaadin users to be able to unit-test components that depend on UI.getCurrent() and similar, which is exactly what [karibu-testing](https://github.com/mvysny/karibu-testing) provides. Could you please add a link to karibu-testing into the `unit-and-integration-testing.adoc` page?

**Comment by tarekoraby** [comment]
@mvysny this issue is now fixed. Right?

**Comment by mvysny** [comment]
I'd say not yet: please take a look at https://github.com/vaadin/docs/pull/1385

**Comment by jouni** [comment]
Karibu testing is linked from https://vaadin.com/docs/latest/tutorial/unit-and-integration-testing
